import {checkpointOneProviderUnknownReceipt,oneProviderUnsettled,type OneProviderReadMedia} from './one-provider-receipt-checkpoint';
import type {patchMediaOperation} from '../store/media-operations';
import {randomUUID,createHash} from 'node:crypto';
import type {IpcMain,IpcMainInvokeEvent} from 'electron';
import {isAppControlEvent} from '../app-control/ipc-registry';
import {ONE_PROVIDER_NATIVE_SCHEMA,type OneProviderBootstrap,type OneProviderPrepared,type OneProviderQuote} from '../../shared/one-provider-native';
import {OneProviderError,type OneProviderAction,type OneProviderReceipt} from '../../shared/one-provider';
import {oneVaultDigest,signOneVault,verifyOneVault} from './one-vault-crypto';
import {oneVaultSlot,type OneVaultSqlite} from './one-vault-journal';
import {loadOneVaultApprovedHost} from './one-vault-service';
import type {OneVaultRuntime,OneVaultOwnerWindow,OneVaultRuntimeAnchor} from './one-vault-runtime';
import {OneProviderNativeBridge,type OneProviderNativeRegistry,type OneProviderNativeAction} from './one-provider-native-bridge';
import {OneProviderReadCore,type OneProviderReadAccess,type OneProviderReadOrigin,type OneProviderReadCorePorts} from './one-provider-read-core';
import type {OneProviderReadProjection} from '../../shared/one-provider-read';
import {type OneProviderLease} from './one-provider-broker';
const sha=(v:string|Uint8Array)=>createHash('sha256').update(v).digest('hex');
export interface OneProviderNativePlan {
 commandId:string;sourceRevision:string;accountLabel:string;roleLabel:string;
 models:Array<{id:string;label:string}>;voices:Array<{id:string;label:string}>;texts:Array<{ref:string;label:string;digest:string}>;
 quote:OneProviderQuote;retention:{enableProviderLogging:boolean;disclosure:string};
 artifactRootRef:string;minDurationMs:number;maxDurationMs:number;
}
export interface OneProviderDomainPorts {
 /** Existing native source/quote owner resolves all options, text refs and resource paths. */
 resolve(commandId:string):Promise<OneProviderNativePlan|null>;
 /** Live domain revision/ACL fence, not an async result cached as allow. */
 stillCurrent(plan:Readonly<OneProviderNativePlan>):boolean;
 readText(ref:string,anchor:Readonly<OneVaultRuntimeAnchor>):Promise<string>;
 approvedArtifactRoot(ref:string,anchor:Readonly<OneVaultRuntimeAnchor>):string|null;
 currentGrant(action:Readonly<OneProviderAction>,phase:'read'|'dispatch'|'publish'):Promise<{decision:'allow'|'deny'|'unknown';lease:OneProviderLease|null}>;
}
interface Held {prepared:OneProviderPrepared;native:OneProviderNativeAction;plan:OneProviderNativePlan}
export interface OneProviderMainPorts {
 runtime():OneVaultRuntime|null;domain:OneProviderDomainPorts|null;
 /** Independent CURRENT retained-resource authority. Missing means retained reads unavailable. */
 retainedReads?:{authorize(origin:Readonly<OneProviderReadOrigin>,...args:Parameters<OneProviderReadCorePorts['authorize']> extends [unknown,...infer Rest]?Rest:never):ReturnType<OneProviderReadCorePorts['authorize']>;storageProjection?(origin:Readonly<OneProviderReadOrigin>,commandId:string):ReturnType<NonNullable<OneProviderReadCorePorts['storageProjection']>>;approvedArtifactRoot?(origin:Readonly<OneProviderReadOrigin>,...args:Parameters<NonNullable<OneProviderReadCorePorts['approvedArtifactRoot']>> extends [unknown,...infer Rest]?Rest:never):string|null};
 /** Real native authenticated channel WeakMap + current approved paired sender. Never a bearer/IPC-shaped object. */
 remoteReadOrigin?(origin:object):OneProviderReadOrigin|null;
 assertOwner(event:IpcMainInvokeEvent):OneVaultOwnerWindow;
 approve(window:OneVaultOwnerWindow,prepared:Readonly<OneProviderPrepared>,retention:Readonly<OneProviderNativePlan['retention']>):Promise<boolean>;
 /** Native trusted player receives already verified bytes, never a renderer/provider path. */
 playAudio(bytes:Uint8Array,receipt:Readonly<OneProviderReceipt>,stillCurrent:()=>boolean):Promise<void>;
 media:{getMediaOperation(id:string):OneProviderReadMedia|null;patchMediaOperation?:typeof patchMediaOperation};
 bridge?(vault:OneVaultRuntime,registry:OneProviderNativeRegistry):Pick<OneProviderNativeBridge,'executeMainOperation'>;
}
/** Value-free minted action metadata on the SAME original command. Not an effect queue. */
export class OneProviderCommandRegistry {
 constructor(private readonly db:OneVaultSqlite){if(!(db.prepare('PRAGMA table_info(one_supervisor_requests)').all() as Array<{name:string}>).some(c=>c.name==='one_provider_metadata_json'))db.exec('ALTER TABLE one_supervisor_requests ADD COLUMN one_provider_metadata_json TEXT');}
 private row(commandId:string):{one_provider_metadata_json:string|null}|null{return this.db.prepare('SELECT one_provider_metadata_json FROM one_supervisor_requests WHERE command_id=?').get(commandId) as {one_provider_metadata_json:string|null}??null;}
 list(commandId:string):Held[]{const row=this.row(commandId);if(!row)return[];try{const result=row.one_provider_metadata_json?JSON.parse(row.one_provider_metadata_json):[];if(!Array.isArray(result)||result.length>64)throw Error();return result;}catch{throw new OneProviderError('operation_conflict');}}
 get(id:string):Held|null {const row=this.db.prepare("SELECT command_id FROM one_supervisor_requests WHERE EXISTS (SELECT 1 FROM json_each(COALESCE(one_provider_metadata_json,'[]')) WHERE json_extract(value,'$.prepared.operationId')=?)").all(id) as Array<{command_id:string}>;if(row.length!==1)return null;return this.list(row[0].command_id).find(h=>h.prepared.operationId===id)??null;}
 append(commandId:string,expected:Held[],held:Held):void {if(expected.length>=64)throw new OneProviderError('operation_conflict');const row=this.row(commandId);if(!row||oneVaultDigest(this.list(commandId))!==oneVaultDigest(expected))throw new OneProviderError('operation_conflict');const b=held.prepared.action.binding;const result=this.db.prepare("UPDATE one_supervisor_requests SET one_provider_metadata_json=? WHERE command_id=? AND run_id=? AND COALESCE(task_id,'one:'||origin_chat_id)=? AND one_provider_metadata_json IS ?").run(JSON.stringify([...expected,held]),commandId,b.runId,b.taskId,row.one_provider_metadata_json);if(Number(result.changes)!==1)throw new OneProviderError('operation_conflict');}
}
export class OneProviderMain {
 private registry:OneProviderCommandRegistry|null=null;
 private readCoreValue:OneProviderReadCore|null=null;
 private readonly readAccess=new WeakMap<object,{origin:OneProviderReadOrigin;fence():boolean}>();
 constructor(private readonly p:OneProviderMainPorts){}
 private nativeReadOrigin():OneProviderReadOrigin|null {const r=this.vault(),o=r.currentNativeOwner();return o?{principalId:o.principalId,sessionId:o.sessionId,workspaceId:o.workspaceId,hostId:o.hostId,oneId:r.sources.oneId(),originEpoch:oneVaultDigest(o)}:null;}
 private origin(access:OneProviderReadAccess):OneProviderReadOrigin|null {const a=this.readAccess.get(access);try{return a?.fence()&&oneVaultDigest(this.nativeReadOrigin())===oneVaultDigest(a.origin)?a.origin:null}catch{return null}}
 private readFence(access:OneProviderReadAccess):void {if(!this.origin(access))throw new OneProviderError('authority_denied');}
 private desktopReadAccess(event:IpcMainInvokeEvent):OneProviderReadAccess {const window=this.owned(event),origin=this.nativeReadOrigin();if(!origin)throw new OneProviderError('authority_unavailable');const access=Object.freeze({});this.readAccess.set(access,{origin,fence:()=>this.owned(event)===window});return access;}
 private remoteReadAccess(remote:object):OneProviderReadAccess {const origin=this.p.remoteReadOrigin?.(remote),native=this.nativeReadOrigin();if(!origin||!native||oneVaultDigest(origin)!==oneVaultDigest(native))throw new OneProviderError('authority_unavailable');const access=Object.freeze({});this.readAccess.set(access,{origin,fence:()=>oneVaultDigest(this.p.remoteReadOrigin?.(remote))===oneVaultDigest(origin)});return access;}
 private reads():OneProviderReadCore {return this.readCoreValue??=new OneProviderReadCore({origin:a=>this.origin(a),records:{get:id=>this.records().get(id)},media:this.p.media,checkpointUnknown:(row,receipt,current)=>checkpointOneProviderUnknownReceipt(this.vault().sources.db,this.p.media,row,receipt,current),
  approvedSigningKey:(id,key)=>{const r=this.vault(),h=r.trust.currentHostMetadata();return h&&h.hostId===id&&h.hostKeyId===key&&h.revokedAt===null&&r.trust.nativeApprovalValid(h.approvedNativeReceiptId,oneVaultDigest(h))?h.signingPublicKey:null;},
  authorize:async(access,h,receipt,purpose)=>{this.readFence(access);if(!this.valid(h)){const retained=this.p.retainedReads;if(!retained)return null;const result=await retained.authorize(this.origin(access)!,h,receipt,purpose);if(!result)return null;return{...result,stillCurrent:()=>this.p.retainedReads===retained&&!!this.origin(access)&&result.stillCurrent()};}
   const lease=await this.lease(h,purpose==='status'?'read':'publish');this.readFence(access);const currentBinding=this.context(h.prepared.commandId).binding,now=Date.now();
   return{grant:{schema:'agentlas.one-provider-resource-read.v1',oneId:this.origin(access)!.oneId,commandId:h.prepared.commandId,operationId:h.prepared.operationId,actionDigest:oneVaultDigest(h.prepared.action),receiptDigest:oneVaultDigest(receipt),currentBinding,revision:currentBinding.authorityRevision,purpose,issuedAt:now,expiresAt:now+30000},stillCurrent:()=>!!this.origin(access)&&lease.stillCurrent()};},
  unknownReceipt:(access,h)=>this.activeStatus(access,h.prepared.operationId),
  storageProjection:async(access,id)=>{this.readFence(access);const value=await this.activeBootstrap(access,id);if(value.binding){const lease=await this.vault().authority(value.binding,'reconcile'),held=oneVaultDigest(this.scope(id));this.readFence(access);if(!lease.stillCurrent())throw new OneProviderError('authority_denied');return{projection:value,stillCurrent:()=>{try{return !!this.origin(access)&&lease.stillCurrent()&&oneVaultDigest(this.scope(id))===held}catch{return false}}}}const retained=this.p.retainedReads,result=await retained?.storageProjection?.(this.origin(access)!,id);return result?{...result,stillCurrent:()=>this.p.retainedReads===retained&&!!this.origin(access)&&result.stillCurrent()}:null;},
  approvedArtifactRoot:(access,h,g)=>{this.readFence(access);if(!this.valid(h))return this.p.retainedReads?.approvedArtifactRoot?.(this.origin(access)!,h,g)??null;const anchor=this.vault().anchor(h.native.commandId);return anchor?this.p.domain?.approvedArtifactRoot(h.native.artifactRootRef,anchor)??null:null;}});}
 /** Same read core, with independently minted remote origin; no fabricated Electron event. */
 async readRemoteProjection(origin:object,commandId:string,operationId:string|null):Promise<OneProviderReadProjection&{stillCurrent():boolean}>{return this.reads().bootstrap(this.remoteReadAccess(origin),commandId,operationId);}
 async readRemoteAudio(origin:object,commandId:string,operationId:string,receiptDigest:string){return this.reads().acquireAudio(this.remoteReadAccess(origin),commandId,operationId,receiptDigest);}

 private vault():OneVaultRuntime{const r=this.p.runtime();if(!r)throw new OneProviderError('provider_route_unavailable');return r;}
 private records():OneProviderCommandRegistry{return this.registry??=new OneProviderCommandRegistry(this.vault().sources.db);}
 private owned(event:IpcMainInvokeEvent):OneVaultOwnerWindow{if(isAppControlEvent(event))throw new OneProviderError('authority_denied');const w=this.p.assertOwner(event);if(w.isDestroyed()||!w.isFocused())throw new OneProviderError('authority_denied');return w;}
 private exact(raw:unknown,keys:string[]):Record<string,unknown>{if(!raw||typeof raw!=='object'||Array.isArray(raw)||Object.keys(raw).sort().join('|')!==[...keys].sort().join('|'))throw new OneProviderError('authority_denied');return raw as Record<string,unknown>;}
 private id(v:unknown):string {if(typeof v!=='string'||!v||v.length>200||!/^[-A-Za-z0-9._:/]+$/.test(v))throw new OneProviderError('authority_denied');return v;}
 private scope(commandId:string){const r=this.vault(),c=r.resolveCommand(commandId),reference=r.currentStoredReference(commandId,'elevenlabs-audio','ELEVENLABS_API_KEY'),m=reference?r.metadata.read(reference.request.binding.commandId):r.metadata.read(commandId),host=r.trust.currentHostMetadata();if(m?.request.binding.commandId!==commandId&&(!reference||!reference.stillCurrent()||m?.operationId!==reference.operationId||oneVaultDigest(m.request)!==oneVaultDigest(reference.request)||!c||c.binding.expectedGeneration!==reference.generation||oneVaultSlot({binding:{...m.request.binding,...c.binding}} as import('../../shared/one-vault').OneVaultRequest)!==reference.slotId))throw new OneProviderError('authority_unavailable');if(!c||!m||!host||m.request.hostKeyId!==host.hostKeyId||m.request.recipientKeyId!==host.recipientKeyId||m.request.binding.hostId!==host.hostId||m.request.binding.trustGeneration!==host.generation||!verifyOneVault('request',m.request,host.signingPublicKey))throw new OneProviderError('authority_unavailable');return{c,m,host,binding:{...m.request.binding,...c.binding}};}
 private context(commandId:string){const r=this.vault(),s=this.scope(commandId),{c,m}=s,op=m.operationId?r.journal.get(m.operationId):null,slot=r.journal.current(oneVaultSlot(m.request));if(!op||op.state!=='saved'||op.requestDigest!==oneVaultDigest(m.request)||slot.pendingOperation!==null||slot.credentialRef!==op.credentialRef||slot.generation!==op.generation||c.binding.expectedGeneration!==op.generation)throw new OneProviderError('generation_changed');return{...s,op};}
 private async knownStorage(access:OneProviderReadAccess,commandId:string,errorCode:OneProviderBootstrap['errorCode']):Promise<OneProviderBootstrap|null>{
  try{const r=this.vault(),s=this.scope(commandId),lease=await r.authority(s.m.request.binding,'reconcile');this.readFence(access);if(!lease.stillCurrent()||oneVaultDigest(this.scope(commandId))!==oneVaultDigest(s))return null;
   const op=s.m.operationId?r.journal.get(s.m.operationId):null,slot=r.journal.current(oneVaultSlot(s.m.request));
   const saved=!!op&&op.state==='saved'&&op.requestDigest===oneVaultDigest(s.m.request)&&slot.pendingOperation===null&&slot.credentialRef===op.credentialRef&&slot.generation===op.generation;
   const active=this.records().list(commandId).at(-1)??null;let receipt:OneProviderReceipt|null=null;

   this.readFence(access);if(!lease.stillCurrent()||oneVaultDigest(this.scope(commandId))!==oneVaultDigest(s))return null;
   return{schema:ONE_PROVIDER_NATIVE_SCHEMA,state:saved?'key-saved':'key-missing',commandId,bindingKey:oneVaultDigest(s.binding),binding:s.binding,credentialGeneration:saved?slot.generation:null,accountLabel:s.c.accountLabel,roleLabel:s.binding.scope==='personal'?'Personal':'Organization',permittedModels:active&&this.valid(active)?active.plan.models:[],permittedVoices:active&&this.valid(active)?active.plan.voices:[],permittedTextRefs:active&&this.valid(active)?active.plan.texts:[],quote:null,retention:active&&this.valid(active)?active.plan.retention:{enableProviderLogging:false,disclosure:''},activeOperation:active&&this.valid(active)?active.prepared:null,receipt,resourceGrant:null,pinnedHost:{hostId:s.host.hostId,hostKeyId:s.host.hostKeyId,publicKey:s.host.signingPublicKey,trustGeneration:s.host.generation},observedAt:Date.now(),expiresAt:Date.now()+30000,errorCode};
  }catch{return null;}
 }
 private valid(h:Held):boolean {try{
  const c=this.context(h.prepared.commandId),a=h.prepared.action,n=h.native,p=h.plan,text=p.texts.find(t=>t.ref===n.textRef);
  const expected:OneProviderNativeAction={operationId:a.operationId,commandId:h.prepared.commandId,vaultRequestDigest:oneVaultDigest(c.m.request),currentBindingDigest:oneVaultDigest(c.c.binding),kind:a.kind,modelId:a.modelId,voiceId:a.voiceId,outputFormat:a.outputFormat,textDigest:a.textDigest,textRef:a.kind==='verify'?'':n.textRef,artifactRootRef:p.artifactRootRef,minDurationMs:a.minDurationMs,maxDurationMs:a.maxDurationMs,expiresAt:a.expiresAt,enableProviderLogging:a.enableProviderLogging};
  return !!this.p.domain?.stillCurrent(p)&&h.prepared.schema===ONE_PROVIDER_NATIVE_SCHEMA&&a.schema==='agentlas.one-provider.v1'&&a.operationId===h.prepared.operationId&&p.commandId===h.prepared.commandId
   &&h.prepared.bindingKey===oneVaultDigest(c.binding)&&oneVaultDigest(a.binding)===oneVaultDigest(c.binding)&&a.credentialGeneration===c.op.generation
   &&oneVaultDigest(n)===oneVaultDigest(expected)&&oneVaultDigest(h.prepared.quote)===oneVaultDigest(p.quote)&&a.expiresAt===p.quote.expiresAt
   &&p.models.some(m=>m.id===a.modelId)&&p.voices.some(v=>v.id===a.voiceId)&&a.modelId==='eleven_multilingual_v2'&&a.outputFormat==='pcm_24000'
   &&a.minDurationMs===p.minDurationMs&&a.maxDurationMs===p.maxDurationMs&&a.enableProviderLogging===p.retention.enableProviderLogging
   &&(a.kind==='verify'?a.textDigest===sha(''):a.kind==='tts'&&!!text&&text.digest===a.textDigest);
 }catch{return false;}}
 private async plan(commandId:string):Promise<{plan:OneProviderNativePlan;context:ReturnType<OneProviderMain['context']>}>{const c=this.context(commandId),d=this.p.domain;if(!d)throw new OneProviderError('provider_route_unavailable');const plan=await d.resolve(commandId);if(!plan||plan.commandId!==commandId||!plan.sourceRevision||!d.stillCurrent(plan)||oneVaultDigest(this.context(commandId))!==oneVaultDigest(c))throw new OneProviderError('authority_unavailable');if(!plan.models.length||!plan.voices.length||!plan.quote||plan.quote.expiresAt<=Date.now()||!Number.isSafeInteger(plan.quote.upperBoundMinor)||plan.quote.upperBoundMinor<0||!c.binding.cost||plan.quote.currency!==c.binding.cost.currency||plan.quote.consentRevision!==c.binding.cost.consentRevision||plan.quote.upperBoundMinor>c.binding.cost.maxMinor||plan.quote.payerId!==c.binding.payerId)throw new OneProviderError('cost_unknown');return{plan:structuredClone(plan),context:c};}
 private async lease(h:Held,phase:'read'|'dispatch'|'publish'){if(!this.valid(h)||!this.p.domain)throw new OneProviderError('authority_denied');const native=await this.vault().authority(h.prepared.action.binding,`provider-${phase}`),domain=await this.p.domain.currentGrant(h.prepared.action,phase);if(domain.decision!=='allow'||!domain.lease||!native.stillCurrent()||!domain.lease.stillCurrent()||!this.valid(h))throw new OneProviderError('authority_unavailable');return{stillCurrent:()=>native.stillCurrent()&&!!domain.lease?.stillCurrent()&&this.valid(h)};}
 private async activeBootstrap(access:OneProviderReadAccess,commandId:string):Promise<OneProviderBootstrap>{this.readFence(access);try{const {plan,context:c}=await this.plan(commandId);this.readFence(access);const rows=this.records().list(commandId),active=rows.at(-1)??null;let receipt:OneProviderReceipt|null=null;return{schema:ONE_PROVIDER_NATIVE_SCHEMA,state:'verification-required',commandId,bindingKey:oneVaultDigest(c.binding),binding:c.binding,credentialGeneration:c.op.generation,accountLabel:plan.accountLabel,roleLabel:plan.roleLabel,permittedModels:plan.models,permittedVoices:plan.voices,permittedTextRefs:plan.texts,quote:plan.quote,retention:plan.retention,activeOperation:active&&this.valid(active)?active.prepared:null,receipt,resourceGrant:null,pinnedHost:{hostId:c.host.hostId,hostKeyId:c.host.hostKeyId,publicKey:c.host.signingPublicKey,trustGeneration:c.host.generation},observedAt:Date.now(),expiresAt:plan.quote.expiresAt,errorCode:null};}catch(e){const code=e instanceof OneProviderError?e.code:'authority_unavailable',known=await this.knownStorage(access,commandId,code);if(known)return known;return{schema:ONE_PROVIDER_NATIVE_SCHEMA,state:'unavailable',commandId,bindingKey:'',binding:null,credentialGeneration:null,accountLabel:'',roleLabel:'',permittedModels:[],permittedVoices:[],permittedTextRefs:[],quote:null,retention:{enableProviderLogging:false,disclosure:''},activeOperation:null,receipt:null,resourceGrant:null,pinnedHost:null,observedAt:Date.now(),expiresAt:Date.now(),errorCode:e instanceof OneProviderError?e.code:'authority_unavailable'};}}
 async bootstrap(event:IpcMainInvokeEvent,raw:unknown):Promise<OneProviderBootstrap>{const access=this.desktopReadAccess(event),i=this.exact(raw,['commandId']),commandId=this.id(i.commandId);try{return(await this.reads().bootstrap(access,commandId)).projection;}catch(e){this.readFence(access);return{schema:ONE_PROVIDER_NATIVE_SCHEMA,state:'unavailable',commandId,bindingKey:'',binding:null,credentialGeneration:null,accountLabel:'',roleLabel:'',permittedModels:[],permittedVoices:[],permittedTextRefs:[],quote:null,retention:{enableProviderLogging:false,disclosure:''},activeOperation:null,receipt:null,resourceGrant:null,pinnedHost:null,observedAt:Date.now(),expiresAt:Date.now(),errorCode:e instanceof OneProviderError?e.code:'authority_unavailable'};}}
 async prepare(event:IpcMainInvokeEvent,raw:unknown):Promise<OneProviderPrepared>{this.owned(event);const i=this.exact(raw,['commandId','kind','modelId','voiceId','textRef']),commandId=this.id(i.commandId);if(!['verify','tts'].includes(String(i.kind)))throw new OneProviderError('authority_denied');const {plan,context:c}=await this.plan(commandId);this.owned(event);const text=plan.texts.find(t=>t.ref===i.textRef);if(!plan.models.some(m=>m.id===i.modelId)||i.modelId!=='eleven_multilingual_v2'||!plan.voices.some(v=>v.id===i.voiceId)||(i.kind==='tts'?!text:i.textRef!==null))throw new OneProviderError('input_changed');const prior=this.records().list(commandId),last=prior.at(-1);if(last){const effect=this.p.media.getMediaOperation(last.prepared.operationId);if(!effect||!['succeeded','failed'].includes(effect.lifecycle)){if(this.valid(last)&&last.prepared.action.kind===i.kind&&last.prepared.action.modelId===i.modelId&&last.prepared.action.voiceId===i.voiceId&&last.native.textRef===(text?.ref??'')&&oneVaultDigest(last.plan)===oneVaultDigest(plan))return last.prepared;throw new OneProviderError('operation_conflict');}}
  const operationId=randomUUID(),action:OneProviderAction={schema:'agentlas.one-provider.v1',operationId,kind:i.kind as 'verify'|'tts',binding:c.binding,credentialGeneration:c.op.generation,modelId:String(i.modelId),voiceId:String(i.voiceId),outputFormat:'pcm_24000',textDigest:text?.digest??sha(''),minDurationMs:plan.minDurationMs,maxDurationMs:plan.maxDurationMs,expiresAt:plan.quote.expiresAt,enableProviderLogging:plan.retention.enableProviderLogging},prepared:OneProviderPrepared={schema:ONE_PROVIDER_NATIVE_SCHEMA,commandId,bindingKey:oneVaultDigest(c.binding),operationId,action,quote:plan.quote},native:OneProviderNativeAction={operationId,commandId,vaultRequestDigest:oneVaultDigest(c.m.request),currentBindingDigest:oneVaultDigest(c.c.binding),kind:action.kind,modelId:action.modelId,voiceId:action.voiceId,outputFormat:action.outputFormat,textDigest:action.textDigest,textRef:text?.ref??'',artifactRootRef:plan.artifactRootRef,minDurationMs:action.minDurationMs,maxDurationMs:action.maxDurationMs,expiresAt:action.expiresAt,enableProviderLogging:action.enableProviderLogging},held={prepared,native,plan};const lease=await this.lease(held,'read');this.owned(event);if(!lease.stillCurrent())throw new OneProviderError('authority_denied');this.records().append(commandId,prior,held);return prepared;
 }
 async execute(event:IpcMainInvokeEvent,raw:unknown):Promise<OneProviderReceipt>{const window=this.owned(event),i=this.exact(raw,['operationId']),id=this.id(i.operationId),h=this.records().get(id);if(!h||!this.valid(h))throw new OneProviderError('authority_denied');if(this.p.media.getMediaOperation(id))return this.status(event,{operationId:id});const before=await this.plan(h.prepared.commandId);if(oneVaultDigest(before.plan)!==oneVaultDigest(h.plan)||!await this.p.approve(window,Object.freeze(structuredClone(h.prepared)),Object.freeze(structuredClone(h.plan.retention))))throw new OneProviderError('authority_denied');this.owned(event);const after=await this.plan(h.prepared.commandId);if(oneVaultDigest(after.plan)!==oneVaultDigest(h.plan)||!this.valid(h))throw new OneProviderError('authority_denied');const lease=await this.lease(h,'dispatch');this.owned(event);if(!lease.stillCurrent())throw new OneProviderError('authority_denied');const r=this.vault(),d=this.p.domain!,registry:OneProviderNativeRegistry={current:operationId=>{const record=this.records().get(operationId);return record&&this.valid(record)?record.native:null;},readText:(ref,anchor)=>d.readText(ref,anchor),approvedArtifactRoot:(ref,anchor)=>d.approvedArtifactRoot(ref,anchor),currentGrant:(action,phase)=>d.currentGrant(action,phase)};const bridge=this.p.bridge?.(r,registry)??new OneProviderNativeBridge(r,registry);return bridge.executeMainOperation(id);}
 private async activeStatus(access:OneProviderReadAccess,id:string):Promise<OneProviderReceipt>{this.readFence(access);const h=this.records().get(id);if(!h||!this.valid(h))throw new OneProviderError('authority_denied');const lease=await this.lease(h,'read'),media=this.p.media.getMediaOperation(id),r=this.vault(),c=this.context(h.prepared.commandId);this.readFence(access);if(!lease.stillCurrent())throw new OneProviderError('authority_denied');if(media&&media.inputDigest!==oneVaultDigest(h.prepared.action))throw new OneProviderError('operation_conflict');const receipt=(media?.result?.receipt??(media?.providerCheckpoint as {oneProviderReceipt?:unknown}|null)?.oneProviderReceipt) as OneProviderReceipt|null;
  if(receipt){const b=h.prepared.action.binding,scope={taskId:b.taskId,runId:b.runId,controlVersion:b.controlVersion,authorityRevision:b.authorityRevision,permissionRevision:b.permissionRevision,hostId:b.hostId,principalId:b.principalId,organizationId:b.organizationId,workspaceId:b.workspaceId,resourceId:b.resourceId,provider:b.provider,providerWorkspace:b.providerWorkspace,region:b.region,credentialGeneration:h.prepared.action.credentialGeneration};if(!Object.entries(scope).every(([k,v])=>(receipt as unknown as Record<string,unknown>)[k]===v)||!Number.isSafeInteger(receipt.observedAt)||receipt.observedAt<0||receipt.observedAt>Date.now()+5000||!verifyOneVault('receipt',receipt,c.host.signingPublicKey)||receipt.hostKeyId!==c.host.hostKeyId||receipt.operationId!==id||receipt.actionDigest!==oneVaultDigest(h.prepared.action)||(['audio_ready','verified'].includes(receipt.state)&&media?.lifecycle!=='succeeded'))throw new OneProviderError('operation_conflict');return receipt;}
  if(!oneProviderUnsettled(media))throw new OneProviderError('operation_conflict');
  const host=await loadOneVaultApprovedHost(c.host.hostId,r.trust,r.sources.vault);this.readFence(access);if(!lease.stillCurrent()||oneVaultDigest(host.metadata)!==oneVaultDigest(c.host))throw new OneProviderError('authority_denied');const b=h.prepared.action.binding;return signOneVault<OneProviderReceipt>('receipt',{schema:'agentlas.one-provider.v1',operationId:id,actionDigest:oneVaultDigest(h.prepared.action),taskId:b.taskId,runId:b.runId,controlVersion:b.controlVersion,authorityRevision:b.authorityRevision,permissionRevision:b.permissionRevision,hostId:b.hostId,principalId:b.principalId,organizationId:b.organizationId,workspaceId:b.workspaceId,resourceId:b.resourceId,provider:'elevenlabs-audio',providerWorkspace:b.providerWorkspace,region:b.region,credentialGeneration:h.prepared.action.credentialGeneration,state:'outcome_unknown',errorCode:'provider_uncertain',audio:null,observedAt:Date.now(),hostKeyId:host.metadata.hostKeyId,signature:''},host.signingKey);
 }
 async status(event:IpcMainInvokeEvent,raw:unknown):Promise<OneProviderReceipt>{const access=this.desktopReadAccess(event),i=this.exact(raw,['operationId']),id=this.id(i.operationId),h=this.records().get(id);if(!h)throw new OneProviderError('authority_denied');return(await this.reads().readOperation(access,h.prepared.commandId,id)).receipt;}
 async openAudio(event:IpcMainInvokeEvent,raw:unknown):Promise<void>{const access=this.desktopReadAccess(event),i=this.exact(raw,['operationId','receiptDigest']),id=this.id(i.operationId),h=this.records().get(id);if(!h||typeof i.receiptDigest!=='string')throw new OneProviderError('authority_denied');const result=await this.reads().acquireAudio(access,h.prepared.commandId,id,i.receiptDigest);try{this.readFence(access);if(!result.stillCurrent())throw new OneProviderError('authority_denied');await this.p.playAudio(result.bytes,Object.freeze(result.snapshot.receipt),result.stillCurrent);}finally{result.bytes.fill(0);}}

}
export function registerOneProviderMainIpc(input:{ipc:Pick<IpcMain,'handle'>;ports:OneProviderMainPorts}):OneProviderMain {const value=new OneProviderMain(input.ports);for(const method of ['bootstrap','prepare','execute','status','openAudio'] as const)input.ipc.handle(`oneProvider:${method}`,async(event,raw,...extra)=>{if(extra.length)throw new OneProviderError('authority_denied');try{return await value[method](event,raw);}catch(e){throw new OneProviderError(e instanceof OneProviderError?e.code:'provider_route_unavailable');}});return value;}
