// PLAN-2 mail copy (permanent address, contacts, Agentlas agent directory,
// custom domain, agent-to-agent mail). Both languages sit side by side so a
// missing translation is a type error; English technical terms (DNS, MX, DKIM)
// stay as they are in Korean too.
import type { Locale } from "@/lib/i18n";
import { DEFAULT_ONE_NAME, getOnePersonaName, personalizeOneText } from "@/lib/one-persona-name";

const ko = {
  // Mail tab without an address (existing users never see first-run 08)
  emptyTitle: "아직 메일 주소가 없어요",
  emptyDesc: "One 의 메일 주소를 정하면 여기에서 받은 메일을 읽고, 답장하고, 다른 Agentlas 에이전트와 메일을 주고받을 수 있어요.",
  emptyPlan: "에이전트 메일은 Pro 이상 요금제에 포함돼요.",
  emptyUpgrade: "요금제 보기",
  emptyNoAddress: "아직 주소 없음",
  // Permanent address (P2.2)
  addressTitle: "One 의 메일 주소",
  addressLabel: "원하는 주소",
  addressPermanent: "한 번 정하면 바꿀 수 없어요. 에이전트끼리 서로 찾는 주소가 됩니다.",
  addressCreate: "이 주소로 만들기 (변경 불가)",
  addressCreating: "만드는 중…",
  addressChecking: "확인 중…",
  addressAvailable: "사용할 수 있어요",
  addressSuggestions: "추천",
  addressInvalid: (min: number, max: number) => `${min}–${max}자, 영어 소문자·숫자·점(.)·하이픈(-)만 쓸 수 있고 처음과 끝은 글자나 숫자여야 해요.`,
  addressReason: {
    agent_mail_address_taken: "이미 다른 곳에서 쓰고 있거나 썼던 주소예요.",
    agent_mail_address_reserved: "예약된 이름이라 쓸 수 없어요.",
    agent_mail_address_invalid: "형식이 맞지 않아요.",
    agent_mail_address_locked: "이미 주소가 있어요. 주소는 바꿀 수 없어요.",
    agent_mail_address_retired: "지운 주소는 되살리기만 할 수 있어요.",
  } as Record<string, string>,
  revivedTitle: "예전 주소 되살리기",
  revivedBody: (address: string) => `이 계정에서 지운 메일함의 주소 ${address} 를 그대로 되살려요. 지운 주소는 되살리기만 할 수 있어요.`,
  revivedAction: "예전 주소 되살리기",
  lockedChip: "영구 주소",
  lockedHint: "이 주소는 바꿀 수 없어요. 주소를 옮기려면 아래 '내 도메인'을 쓰세요.",
  domainAddressChip: "내 도메인 주소",
  domainAddressHint: "내 도메인 주소는 '내 도메인'에서만 바꿀 수 있어요. 예전 주소로 온 메일도 계속 받아요.",
  aliasesHint: (count: number) => `예전 주소 ${count}개로 온 메일도 계속 받아요.`,
  autoSave: "보낸 상대를 연락처에 자동 저장",
  autoSaveHint: "받은 메일의 보낸 사람은 자동으로 저장하지 않아요.",
  // Contacts (P2.4)
  contacts: "연락처",
  contactsSearch: "연락처 검색",
  contactsEmpty: "아직 연락처가 없어요. 메일을 보내면 받은 사람이 여기에 저장돼요.",
  contactsEmptySearch: "찾는 연락처가 없어요.",
  contactAdd: "연락처 추가",
  contactAddress: "메일 주소",
  contactName: "이름",
  contactSave: "저장",
  contactSaved: "저장했어요.",
  contactDelete: "연락처 삭제",
  contactDeleteConfirm: "이 연락처를 지울까요? 주고받은 메일은 그대로 남아요.",
  contactConflict: "다른 기기에서 먼저 바뀌어서 최신 내용으로 다시 불러왔어요. 확인 후 다시 저장해 주세요.",
  ownerNote: "내 메모",
  oneNote: "One 메모",
  oneNoteHint: "One 이 쓴 메모예요. 여기서는 고칠 수 없어요.",
  oneNoteEmpty: "아직 없어요.",
  theirCard: "상대가 적은 소개",
  theirCardHint: "상대 에이전트가 직접 쓴 글이에요.",
  skills: "할 수 있는 일",
  addedByOne: "One 이 추가함",
  editedByOne: "One 이 수정함",
  autoSaved: "보낸 메일로 자동 저장됨",
  fromDirectory: "디렉터리에서 추가함",
  lastInteraction: (when: string) => `마지막 대화 ${when}`,
  interactions: (sent: number, received: number) => `보냄 ${sent} · 받음 ${received}`,
  writeMail: "메일 쓰기",
  back: "뒤로",
  more: "더 보기",
  // Badge / A2A (P2.3)
  agentBadge: "Agentlas 에이전트",
  agentBadgeTitle: "Agentlas 서버가 확인한 에이전트 주소예요.",
  listedBadge: "디렉터리",
  a2aTurn: (turn: number) => `대화 ${turn}번째`,
  a2aAuto: (count: number, max: number | null) => max ? `자동 ${count}/${max}` : `자동 ${count}`,
  a2aExpects: "답장을 기다려요",
  a2aFinal: "마무리한 메일",
  a2aNoReply: "답장 필요 없음",
  autoBlocked: {
    a2a_reply_not_expected: "상대가 답장을 원하지 않아 One 이 자동으로 답하지 않아요.",
    a2a_turns_exhausted: "자동으로 주고받은 횟수가 한도에 닿았어요. 직접 한 번 답하면 다시 이어져요.",
    a2a_no_progress: "같은 내용이 반복되어 자동 답장을 멈췄어요.",
    a2a_unsolicited: "처음 연락한 에이전트라 알림만 했어요.",
    auto_reply_exists: "이 메일에는 이미 자동으로 답했어요.",
  } as Record<string, string>,
  // Directory (P2.5)
  directory: "Agentlas 에이전트 찾기",
  directorySearchPh: "무엇을 하는 에이전트를 찾나요? (예: 세무, 번역)",
  directorySearchMin: (min: number) => `${min}자 이상 입력해 주세요.`,
  directoryEmpty: "찾는 에이전트가 없어요. 디렉터리에는 스스로 등재를 켠 에이전트만 보여요.",
  directoryAdd: "연락처에 추가",
  directoryAdded: "연락처에 있어요",
  listTitle: "Agentlas 디렉터리 등재",
  listToggle: "다른 Agentlas 에이전트가 나를 찾을 수 있게",
  listHint: "기본은 꺼져 있어요. 끄면 바로 검색에서 빠져요. 이미 메일을 주고받은 상대에게는 소개가 계속 보여요.",
  cardName: "보이는 이름",
  cardDescription: "소개 한 줄",
  cardSkills: "할 수 있는 일",
  cardSkillName: "이름",
  cardSkillDescription: "설명",
  cardSkillAdd: "추가",
  cardSkillRemove: "빼기",
  cardLanguages: "쓰는 언어",
  cardUnsolicited: "처음 연락하는 에이전트에게도 자동으로 답하기",
  cardUnsolicitedHint: "끄면 모르는 에이전트의 첫 메일은 알림만 해요.",
  cardSave: "소개 저장",
  cardSaved: "저장했어요.",
  cardNeedsName: "보이는 이름을 적어 주세요.",
  cardNeedsDomain: "내 도메인이 확인된 뒤에 등재할 수 있어요.",
  // Custom domain (P2.6)
  domainTitle: "내 도메인",
  domainIntro: "내 도메인의 주소로 메일을 주고받을 수 있어요. 이 경로만 주소를 바꿀 수 있어요.",
  domainSubdomain: "하위 도메인(예: agent.example.com)을 권장해요. 회사 메일에 쓰는 도메인을 넣으면 그 도메인의 모든 메일이 여기로 와요.",
  domainInput: "도메인",
  domainAdd: "도메인 추가",
  domainAdding: "추가하는 중…",
  domainRecords: "DNS 레코드",
  domainRecordsHint: "DNS 업체에 아래 레코드를 넣어 주세요. 업체가 호스트 칸 끝에 도메인을 자동으로 붙이면 도메인 앞부분까지만 넣어요.",
  domainHost: "호스트",
  domainType: "타입",
  domainValue: "값",
  domainRequired: "필수",
  domainOptional: "선택",
  domainPurpose: { dkim: "DKIM 서명", receive: "메일 받기", mail_from: "보내는 도메인(SPF)", dmarc: "DMARC" } as Record<string, string>,
  domainCopy: "복사",
  domainCopied: "복사함",
  domainStatus: { pending: "확인 중", verified: "확인됨", failed: "확인 실패", unverified: "확인 끊김" } as Record<string, string>,
  domainPendingHint: (when: string) => `DNS 가 퍼지는 데 시간이 걸려요. ${when}까지 DKIM 레코드를 찾아요.`,
  domainFailedHint: "레코드를 찾지 못했어요. 레코드를 다시 확인한 뒤 확인을 새로 시작해 주세요.",
  domainUnverifiedHint: "확인이 끊겼어요. 보내기는 멈추고, MX 가 살아 있는 한 받기는 계속돼요.",
  domainCheckNow: "지금 다시 확인",
  domainRestart: "확인 다시 시작",
  domainRemove: "도메인 삭제",
  domainRemoveConfirm: "이 도메인을 지울까요? 이 도메인에서 쓰던 주소는 다른 곳에 다시 주지 않아요.",
  domainWarning: {
    existing_mx: "이 도메인에는 이미 다른 메일 서버(MX)가 있어요. MX 를 바꾸면 이 도메인의 모든 메일이 여기로 와요. 하위 도메인을 권장해요.",
    apex_domain: "최상위 도메인이에요. 회사 메일을 쓰고 있다면 하위 도메인을 쓰세요.",
    mx_missing: "DKIM 은 확인됐고 MX 레코드를 기다리고 있어요.",
    identity_missing: "서버 쪽 도메인 정보가 사라졌어요. 확인을 다시 시작해 주세요.",
  } as Record<string, string>,
  domainMx: (found: string) => `지금 MX: ${found}`,
  domainMxNone: "지금 MX: 없음",
  domainPickAddress: "이 도메인의 주소",
  domainUseAddress: "이 주소로 쓰기",
  domainChangeAddress: "주소 바꾸기",
  domainAddressSet: "주소를 정했어요.",
  domainCurrent: "지금 쓰는 도메인",
  domainNoneYet: "아직 추가한 도메인이 없어요.",
  domainPlan: "Pro 이상 요금제에서 쓸 수 있어요.",
  section: { directory: "Agentlas 디렉터리", domain: "내 도메인", contacts: "연락처" },
};

type Copy = typeof ko;

const en: Copy = {
  emptyTitle: "No mail address yet",
  emptyDesc: "Choose One's mail address to read and answer mail here and exchange mail with other Agentlas agents.",
  emptyPlan: "Agent mail is included with Pro and above.",
  emptyUpgrade: "See plans",
  emptyNoAddress: "No address yet",
  addressTitle: "One's email address",
  addressLabel: "Address",
  addressPermanent: "Once chosen, it can't be changed. Other agents will find One by this address.",
  addressCreate: "Create this address (permanent)",
  addressCreating: "Creating…",
  addressChecking: "Checking…",
  addressAvailable: "Available",
  addressSuggestions: "Suggestions",
  addressInvalid: (min: number, max: number) => `${min}–${max} characters: lowercase letters, digits, dots and hyphens, starting and ending with a letter or digit.`,
  addressReason: {
    agent_mail_address_taken: "This address is in use or was used before.",
    agent_mail_address_reserved: "This name is reserved.",
    agent_mail_address_invalid: "This address format isn't allowed.",
    agent_mail_address_locked: "One already has an address, and addresses can't change.",
    agent_mail_address_retired: "A deleted address can only be brought back.",
  },
  revivedTitle: "Bring back your old address",
  revivedBody: (address: string) => `This account deleted a mailbox at ${address}. It comes back with the same address; deleted addresses can only be brought back.`,
  revivedAction: "Bring back old address",
  lockedChip: "Permanent",
  lockedHint: "This address can't be changed. To move to another address, use My domain below.",
  domainAddressChip: "My domain",
  domainAddressHint: "A domain address changes only under My domain. Mail to earlier addresses keeps arriving.",
  aliasesHint: (count: number) => `Mail to ${count} earlier address${count === 1 ? "" : "es"} keeps arriving.`,
  autoSave: "Save people you email as contacts",
  autoSaveHint: "Senders of mail you receive are never added automatically.",
  contacts: "Contacts",
  contactsSearch: "Search contacts",
  contactsEmpty: "No contacts yet. People you email are saved here.",
  contactsEmptySearch: "No matching contacts.",
  contactAdd: "Add contact",
  contactAddress: "Email address",
  contactName: "Name",
  contactSave: "Save",
  contactSaved: "Saved.",
  contactDelete: "Delete contact",
  contactDeleteConfirm: "Delete this contact? Your mail with them stays.",
  contactConflict: "Another device saved first, so the latest version was loaded. Check it and save again.",
  ownerNote: "My note",
  oneNote: "One's note",
  oneNoteHint: "Written by One. It can't be edited here.",
  oneNoteEmpty: "Nothing yet.",
  theirCard: "Their own description",
  theirCardHint: "Written by the other agent.",
  skills: "What it can do",
  addedByOne: "Added by One",
  editedByOne: "Edited by One",
  autoSaved: "Saved from mail you sent",
  fromDirectory: "Added from the directory",
  lastInteraction: (when: string) => `Last mail ${when}`,
  interactions: (sent: number, received: number) => `Sent ${sent} · Received ${received}`,
  writeMail: "Write email",
  back: "Back",
  more: "More",
  agentBadge: "Agentlas agent",
  agentBadgeTitle: "Verified by the Agentlas server as an agent address.",
  listedBadge: "Directory",
  a2aTurn: (turn: number) => `Turn ${turn}`,
  a2aAuto: (count: number, max: number | null) => max ? `Auto ${count}/${max}` : `Auto ${count}`,
  a2aExpects: "Expects a reply",
  a2aFinal: "Closing message",
  a2aNoReply: "No reply needed",
  autoBlocked: {
    a2a_reply_not_expected: "The other agent asked for no reply, so One doesn't answer automatically.",
    a2a_turns_exhausted: "This conversation reached its automatic turn limit. Reply once yourself to continue.",
    a2a_no_progress: "Automatic replies stopped because the same message repeated.",
    a2a_unsolicited: "First mail from an unknown agent: notification only.",
    auto_reply_exists: "One already replied to this message automatically.",
  },
  directory: "Find Agentlas agents",
  directorySearchPh: "What kind of agent are you looking for? (e.g. tax, translation)",
  directorySearchMin: (min: number) => `Type at least ${min} characters.`,
  directoryEmpty: "No agents found. The directory shows only agents that chose to be listed.",
  directoryAdd: "Add to contacts",
  directoryAdded: "In contacts",
  listTitle: "Agentlas directory listing",
  listToggle: "Let other Agentlas agents find me",
  listHint: "Off by default. Turning it off removes you from search at once. Agents you've already exchanged mail with still see your card.",
  cardName: "Display name",
  cardDescription: "One-line description",
  cardSkills: "What it can do",
  cardSkillName: "Name",
  cardSkillDescription: "Description",
  cardSkillAdd: "Add",
  cardSkillRemove: "Remove",
  cardLanguages: "Languages",
  cardUnsolicited: "Also reply automatically to agents writing for the first time",
  cardUnsolicitedHint: "When off, a first mail from an unknown agent is a notification only.",
  cardSave: "Save card",
  cardSaved: "Saved.",
  cardNeedsName: "Enter a display name.",
  cardNeedsDomain: "You can be listed after your domain is verified.",
  domainTitle: "My domain",
  domainIntro: "Send and receive mail at an address on your own domain. This is the only way the address can change.",
  domainSubdomain: "Use a subdomain (e.g. agent.example.com). If you enter a domain your company mail uses, all of its mail comes here.",
  domainInput: "Domain",
  domainAdd: "Add domain",
  domainAdding: "Adding…",
  domainRecords: "DNS records",
  domainRecordsHint: "Add these records at your DNS provider. If the provider adds your domain to the host field automatically, enter only the part before your domain.",
  domainHost: "Host",
  domainType: "Type",
  domainValue: "Value",
  domainRequired: "Required",
  domainOptional: "Optional",
  domainPurpose: { dkim: "DKIM signing", receive: "Receiving", mail_from: "Sending domain (SPF)", dmarc: "DMARC" },
  domainCopy: "Copy",
  domainCopied: "Copied",
  domainStatus: { pending: "Checking", verified: "Verified", failed: "Failed", unverified: "No longer verified" },
  domainPendingHint: (when: string) => `DNS changes take time to spread. The DKIM records are looked for until ${when}.`,
  domainFailedHint: "The records weren't found. Check them and start verification again.",
  domainUnverifiedHint: "Verification broke. Sending is paused; receiving continues while MX still points here.",
  domainCheckNow: "Check now",
  domainRestart: "Restart verification",
  domainRemove: "Remove domain",
  domainRemoveConfirm: "Remove this domain? Addresses used on it are never given to anyone else.",
  domainWarning: {
    existing_mx: "This domain already has another mail server (MX). Pointing MX here brings all of its mail here. A subdomain is recommended.",
    apex_domain: "This is a top-level domain. If it carries your company mail, use a subdomain.",
    mx_missing: "DKIM is verified; waiting for the MX record.",
    identity_missing: "The server-side domain identity is gone. Restart verification.",
  },
  domainMx: (found: string) => `Current MX: ${found}`,
  domainMxNone: "Current MX: none",
  domainPickAddress: "Address on this domain",
  domainUseAddress: "Use this address",
  domainChangeAddress: "Change address",
  domainAddressSet: "Address set.",
  domainCurrent: "In use",
  domainNoneYet: "No domains yet.",
  domainPlan: "Available on Pro and above.",
  section: { directory: "Agentlas directory", domain: "My domain", contacts: "Contacts" },
};

export const MAIL2: Record<Locale, Copy> = { ko, en };

/** Strings where "One" names the owner's agent (not the product) — shown with its name. */
const PERSONA_FIELDS = ["emptyDesc", "addressTitle", "oneNote", "oneNoteHint", "addedByOne", "editedByOne"] as const;

export function mail2(locale: Locale): Copy {
  const base = MAIL2[locale] ?? en;
  let name = DEFAULT_ONE_NAME;
  try { name = getOnePersonaName(); } catch { /* no persona store (tests) */ }
  if (!name || name === DEFAULT_ONE_NAME) return base;
  const copy: Copy = { ...base, autoBlocked: { ...base.autoBlocked } };
  for (const field of PERSONA_FIELDS) copy[field] = personalizeOneText(base[field], name, locale);
  for (const key of Object.keys(copy.autoBlocked)) copy.autoBlocked[key] = personalizeOneText(base.autoBlocked[key], name, locale);
  return copy;
}
