const command = {type:"string",minLength:3,maxLength:200,description:"Stable command ID. Reuse the same ID on an uncertain retry."};
const task = {type:"string",minLength:3,maxLength:200};
const brief = {type:"string",minLength:1,maxLength:8000};
export const ONE_SUPERVISOR_TOOLS = [
  {name:"one_supervisor_status",description:"Read the personal One's current independently owned Work/Science tasks immediately. No waiting, restart, steering or cancellation. Optionally retrieve one exact task's result. Use controlVersion from this observation for control.",annotations:{readOnlyHint:true},inputSchema:{type:"object",properties:{task_id:task},additionalProperties:false}},
  {name:"one_supervisor_start_work",description:"Hand substantial work to the existing local Work executor. Returns a durable task receipt immediately; end this reply and allow unrelated conversation while it works. Does not grant additional permissions. Retry the identical command_id/brief to recover the same receipt.",inputSchema:{type:"object",properties:{command_id:command,brief,project_id:task},required:["command_id","brief"],additionalProperties:false}},
  {name:"one_supervisor_start_science",description:"Start a research request in an existing local Science project/conversation, independently of this reply. The user's computer/service must be connected. Retry using the identical command_id.",inputSchema:{type:"object",properties:{command_id:command,brief,project_id:task},required:["command_id","brief","project_id"],additionalProperties:false}},
  {name:"one_supervisor_control",description:"Steer or explicitly cancel exactly one task after the owner asks. Use its current controlVersion. A vague unrelated message never authorizes cancellation. Returns delivery acknowledgement, not verified application/cleanup. No automatic resume of completed/cancelled tasks.",inputSchema:{type:"object",properties:{command_id:command,task_id:task,control_version:task,action:{type:"string",enum:["steer","cancel"]},message:brief},required:["command_id","task_id","control_version","action"],additionalProperties:false}},
] as const;
export const ONE_SUPERVISOR_TOOL_NAMES=ONE_SUPERVISOR_TOOLS.map(tool=>tool.name);
