const command = {type:"string",minLength:3,maxLength:200,description:"Stable command ID. Reuse the same ID on an uncertain retry."};
const task = {type:"string",minLength:3,maxLength:200};
const brief = {type:"string",minLength:1,maxLength:8000};
export const ONE_SUPERVISOR_TOOLS = [
  {name:"one_supervisor_status",description:"Read the personal One's current independently owned Work/Science tasks immediately. No waiting, restart, steering or cancellation. Optionally retrieve one exact task's result. Use controlVersion from this observation for control.",annotations:{readOnlyHint:true},inputSchema:{type:"object",properties:{task_id:task},additionalProperties:false}},
  {name:"one_supervisor_start_work",description:"Hand substantial work to the existing local Work executor. Returns a durable task receipt immediately; end this reply and allow unrelated conversation while it works. Does not grant additional permissions. Retry the identical command_id/brief to recover the same receipt.",inputSchema:{type:"object",properties:{command_id:command,brief,project_id:task},required:["command_id","brief"],additionalProperties:false}},
  {name:"one_supervisor_start_science",description:"Send a message to a Science project's conversation (thread), independently of this reply: conversation_id picks the thread (one_app_call science.conversations.list), else its open one. Retry with the identical command_id.",inputSchema:{type:"object",properties:{command_id:command,brief,project_id:task,conversation_id:task},required:["command_id","brief","project_id"],additionalProperties:false}},
  {name:"one_chat_send",description:"Send a message as One into an existing Agentlas conversation: a Work session, a teammate's chat or a group room (find chat_id with one_app_call chats.listRecent). It shows as from One. A busy conversation gets it as its next direction. Retry with the identical command_id.",inputSchema:{type:"object",properties:{command_id:command,chat_id:task,message:brief},required:["command_id","chat_id","message"],additionalProperties:false}},
  {name:"one_supervisor_follow_up",description:"Send one more instruction to a delegated Work task whose run has finished (completed or failed), as a new turn in the same Work session. Use it when your review finds something the owner asked for missing or wrong. At most 2 per task; a live run is steered with one_supervisor_control instead; a task the owner cancelled stays cancelled. Retry with the identical command_id.",inputSchema:{type:"object",properties:{command_id:command,task_id:task,message:brief},required:["command_id","task_id","message"],additionalProperties:false}},
  {name:"one_supervisor_checkin",description:"Run a check on your own on a schedule, as the owner asked (\"매일 9시에 점검해\", \"30분마다 로그 봐줘\"). action create: instruction plus every_minutes (5 or more) or daily_at (local HH:MM); notify important (default: message the owner only when something matters) or always. action list, or action cancel with checkin_id. The host wakes you when it is due.",inputSchema:{type:"object",properties:{command_id:command,action:{type:"string",enum:["create","cancel","list"]},instruction:brief,every_minutes:{type:"integer",minimum:5,maximum:10080},daily_at:{type:"string",pattern:"^([01][0-9]|2[0-3]):[0-5][0-9]$"},notify:{type:"string",enum:["important","always"]},checkin_id:task},required:["command_id","action"],additionalProperties:false}},
  {name:"one_supervisor_control",description:"Steer or explicitly cancel exactly one task after the owner asks. Use its current controlVersion. A vague unrelated message never authorizes cancellation. Returns delivery acknowledgement, not verified application/cleanup. No automatic resume of completed/cancelled tasks.",inputSchema:{type:"object",properties:{command_id:command,task_id:task,control_version:task,action:{type:"string",enum:["steer","cancel"]},message:brief},required:["command_id","task_id","control_version","action"],additionalProperties:false}},
  // Owner 2026-10-04: One operates every Agentlas setting and feature, and Science when installed (electron/app-control).
  {name:"one_app_operations",description:"Discover every supported app operation: settings, Work, Graph, Apps, browsers, automations, agents, projects, memory, models, mail, and installed Science. No arguments lists areas with live availability. query (Korean or English) or area finds operations; operation gets one exact operation's JSON input_schema; offset pages through all matches. include_restricted reveals operations owned by human consent or view lifetimes with their reason. Call before one_app_call.",annotations:{readOnlyHint:true},inputSchema:{type:"object",properties:{query:{type:"string",maxLength:200},area:{type:"string",maxLength:120},operation:{type:"string",maxLength:160},limit:{type:"integer",minimum:1,maximum:80},offset:{type:"integer",minimum:0,maximum:10000},include_restricted:{type:"boolean"}},additionalProperties:false}},
  {name:"one_app_call",description:"Do one app operation through the same validation and stores as the owner's click. First discover its exact input_schema and live availability. Destructive or consent actions (delete, stop, resume, install, publish, send, answer) need a turn the owner wrote. ok confirms this call, not asynchronous job completion: inspect result.acknowledgement, state, reason and exact run receipt, then read the target back. Never infer delivery, completion or cleanup from acceptance or a queued message.",inputSchema:{type:"object",properties:{operation:{type:"string",minLength:3,maxLength:160},args:{type:"object"}},required:["operation"],additionalProperties:false}},
] as const;
export const ONE_SUPERVISOR_TOOL_NAMES=ONE_SUPERVISOR_TOOLS.map(tool=>tool.name);
