'use client';
import {useEffect,useRef,useState} from 'react';
import {OneBottomSheet} from '@/components/one/OneBottomSheet';
import {oneVaultCanonical,oneVaultUnsigned} from '@shared/one-vault';
import type {OneProviderResourceReadGrant} from '@shared/one-provider-read';
import type {OneProviderReceipt,OneProviderErrorCode} from '@shared/one-provider';
import {ONE_PROVIDER_NATIVE_SCHEMA,type OneProviderBootstrap,type OneProviderNativeAPI,type OneProviderPrepared} from '@shared/one-provider-native';
import styles from './OneProviderControls.module.css';
const messages:Record<OneProviderErrorCode,string>={authority_denied:'계정·역할 또는 권한이 바뀌었습니다. 현재 요청을 다시 확인해 주세요.',authority_unavailable:'현재 요청 권한을 확인할 수 없습니다.',generation_changed:'저장된 키가 교체되었습니다. 현재 세대를 다시 확인해 주세요.',input_changed:'원래 음성 입력이 바뀌었습니다.',operation_conflict:'같은 작업의 기록이 충돌합니다.',provider_unauthenticated:'제공자가 키를 인증하지 못했습니다.',provider_expired:'제공자 인증이 만료되었습니다.',provider_revoked:'제공자 권한이 철회되었습니다.',provider_permission:'제공자 권한이 부족합니다.',provider_ip_restricted:'제공자 IP 제한으로 연결할 수 없습니다.',provider_workspace:'제공자 작업공간이 일치하지 않습니다.',provider_region:'제공자 지역이 일치하지 않습니다.',provider_quota:'제공자 사용 한도가 부족합니다.',provider_billing:'제공자 결제 상태를 확인해 주세요.',provider_rate_limited:'제공자 호출 제한에 도달했습니다.',provider_network:'제공자 네트워크 결과를 확인할 수 없습니다.',provider_failure:'제공자 실행이 실패했습니다.',provider_uncertain:'실행 결과가 미확인입니다. 같은 작업 상태만 확인할 수 있습니다.',audio_invalid:'검증된 WAV 오디오 결과가 없습니다.',cost_unknown:'현재 비용 견적을 확인할 수 없습니다.',cost_exceeded:'현재 비용 한도를 넘었습니다.',provider_route_unavailable:'현재 안전한 제공자 경로가 준비되지 않았습니다.'};
function code(error:unknown):OneProviderErrorCode {const value=error instanceof Error?error.message:typeof error==='object'&&error?String((error as {code?:unknown}).code):'';return (Object.keys(messages) as OneProviderErrorCode[]).find(c=>value===c||value.endsWith(': '+c))??'authority_unavailable';}
const encoder=new TextEncoder();
export async function oneProviderReceiptDigest(receipt:OneProviderReceipt){return digest(receipt);}
async function digest(value:unknown){return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',encoder.encode(oneVaultCanonical(value))))).map(v=>v.toString(16).padStart(2,'0')).join('');}
function decode(value:string){if(!/^[A-Za-z0-9_-]+$/.test(value))throw Error('bad_signature');const bytes=Uint8Array.from(atob(value.replace(/-/g,'+').replace(/_/g,'/')),c=>c.charCodeAt(0));return bytes;}
function fresh(boot:OneProviderBootstrap,commandId:string){return boot.schema===ONE_PROVIDER_NATIVE_SCHEMA&&boot.commandId===commandId&&boot.binding?.commandId===commandId&&boot.expiresAt>Date.now()&&boot.observedAt>=Date.now()-120000&&boot.observedAt<=Date.now()+30000;}
function validatePrepared(boot:OneProviderBootstrap,operation:OneProviderPrepared,allowExpired=false){const a=operation.action,q=operation.quote,b=boot.binding;
 if(!b||!boot.pinnedHost||operation.schema!==ONE_PROVIDER_NATIVE_SCHEMA||operation.commandId!==boot.commandId||operation.bindingKey!==boot.bindingKey||operation.operationId!==a.operationId||a.schema!=='agentlas.one-provider.v1'||!['verify','tts'].includes(a.kind)||oneVaultCanonical(a.binding)!==oneVaultCanonical(b)||a.credentialGeneration!==boot.credentialGeneration||!allowExpired&&a.expiresAt<=Date.now())throw Error('authority_denied');
 if(!boot.permittedModels.some(m=>m.id===a.modelId)||!boot.permittedVoices.some(v=>v.id===a.voiceId)||a.outputFormat!=='pcm_24000'||a.enableProviderLogging!==boot.retention.enableProviderLogging||a.kind==='tts'&&!boot.permittedTextRefs.some(t=>t.digest===a.textDigest))throw Error('input_changed');
 if(!allowExpired&&q.expiresAt<=Date.now()||q.payerId!==b.payerId||!b.cost||q.currency!==b.cost.currency||q.consentRevision!==b.cost.consentRevision||!Number.isSafeInteger(q.upperBoundMinor)||q.upperBoundMinor<0||q.upperBoundMinor>b.cost.maxMinor)throw Error('cost_unknown');
}
function retainedBinding(boot:OneProviderBootstrap,operation:OneProviderPrepared){return oneVaultCanonical(operation.action.binding)!==oneVaultCanonical(boot.binding)||operation.action.credentialGeneration!==boot.credentialGeneration;}
function validateOriginalPrepared(boot:OneProviderBootstrap,operation:OneProviderPrepared){const a=operation.action,b=a.binding,q=operation.quote;
 if(!boot.binding||!boot.pinnedHost||operation.schema!==ONE_PROVIDER_NATIVE_SCHEMA||operation.commandId!==boot.commandId||b.commandId!==boot.commandId||operation.operationId!==a.operationId||a.schema!=='agentlas.one-provider.v1'||!['verify','tts'].includes(a.kind)||a.credentialGeneration!==b.expectedGeneration||a.outputFormat!=='pcm_24000'||a.expiresAt!==q.expiresAt||q.payerId!==b.payerId||!b.cost||q.currency!==b.cost.currency||q.consentRevision!==b.cost.consentRevision||!Number.isSafeInteger(q.upperBoundMinor)||q.upperBoundMinor<0||q.upperBoundMinor>b.cost.maxMinor)throw Error('authority_denied');
}
async function validateReadGrant(boot:OneProviderBootstrap,operation:OneProviderPrepared,receipt:OneProviderReceipt,grant:OneProviderResourceReadGrant,purpose:'status'|'audio-acquisition'){
 const now=Date.now(),b=boot.binding!,old=operation.action.binding;
 const keys=['schema','oneId','commandId','operationId','actionDigest','receiptDigest','currentBinding','revision','purpose','issuedAt','expiresAt'];
 if(!grant||Object.keys(grant).length!==keys.length||Object.keys(grant).some(k=>!keys.includes(k))||grant.schema!=='agentlas.one-provider-resource-read.v1'||typeof grant.oneId!=='string'||!grant.oneId||grant.oneId.length>200||grant.commandId!==operation.commandId||grant.operationId!==operation.operationId||grant.actionDigest!==await digest(operation.action)||grant.receiptDigest!==await digest(receipt)||grant.purpose!==purpose||typeof grant.revision!=='string'||!grant.revision||grant.revision.length>200||!Number.isSafeInteger(grant.issuedAt)||grant.issuedAt<now-30000||grant.issuedAt>now+5000||!Number.isSafeInteger(grant.expiresAt)||grant.expiresAt<=now||grant.expiresAt>grant.issuedAt+30000||oneVaultCanonical(grant.currentBinding)!==oneVaultCanonical(b)||boot.bindingKey!==await digest(b)||boot.credentialGeneration!==b.expectedGeneration)throw Error('authority_denied');
 for(const k of ['commandId','taskId','runId','hostId','principalId','scope','organizationId','workspaceId','resourceId','provider','providerWorkspace','region','payerId'] as const)if(b[k]!==old[k])throw Error('authority_denied');
}
export async function authenticateOneProviderReceipt(boot:OneProviderBootstrap,operation:OneProviderPrepared,receipt:OneProviderReceipt,nativeObservation?:OneProviderBootstrap,readPurpose:'status'|'audio-acquisition'='status'):Promise<boolean>{try{
 const retained=retainedBinding(boot,operation);if(retained)validateOriginalPrepared(boot,operation);else validatePrepared(boot,operation,true);
 // Only actual fresh native API reads may supply this observation. The SAME Main core
 // checks current origin/One audience/lease; TTL and the old signature grant no authority.
 const now=Date.now();let historical=false;
 if(nativeObservation){const observed=nativeObservation;
  if(!fresh(observed,operation.commandId)||observed.observedAt<now-30000||observed.observedAt>now+5000||observed.bindingKey!==boot.bindingKey||observed.credentialGeneration!==boot.credentialGeneration||oneVaultCanonical(observed.binding)!==oneVaultCanonical(boot.binding)||oneVaultCanonical(observed.pinnedHost)!==oneVaultCanonical(boot.pinnedHost)||!observed.activeOperation||!observed.receipt||await digest(observed.activeOperation)!==await digest(operation)||await digest(observed.receipt)!==await digest(receipt))return false;
  if(observed.resourceGrant){await validateReadGrant(observed,operation,receipt,observed.resourceGrant,readPurpose);
   if(retained&&(!boot.resourceGrant||observed.resourceGrant.oneId!==boot.resourceGrant.oneId||observed.resourceGrant.revision!==boot.resourceGrant.revision))return false;
  }else if(retained)return false;
  if(!retained)validatePrepared(observed,operation,true);historical=true;
 }else if(retained)return false;
 const a=operation.action,b=a.binding,p=boot.pinnedHost!;oneVaultCanonical(receipt);
 if(retained&&operation.bindingKey!==await digest(b))return false;
 if(receipt.schema!=='agentlas.one-provider.v1'||receipt.operationId!==operation.operationId||receipt.actionDigest!==await digest(a)||receipt.hostKeyId!==p.hostKeyId||receipt.hostId!==p.hostId||b.hostId!==p.hostId||(retained?boot.binding!.trustGeneration:b.trustGeneration)!==p.trustGeneration||receipt.credentialGeneration!==a.credentialGeneration||receipt.provider!=='elevenlabs-audio'||!Number.isSafeInteger(receipt.observedAt)||receipt.observedAt<0||!historical&&receipt.observedAt<Date.now()-120000||receipt.observedAt>Date.now()+30000)return false;
 for(const k of ['taskId','runId','controlVersion','authorityRevision','permissionRevision','principalId','organizationId','workspaceId','resourceId','providerWorkspace','region'] as const)if(receipt[k]!==b[k])return false;
 if(!['verified','audio_ready','failed','outcome_unknown'].includes(receipt.state)||receipt.errorCode!==null&&!Object.hasOwn(messages,receipt.errorCode))return false;
 if(receipt.state==='verified'&&(a.kind!=='verify'||receipt.audio!==null||receipt.errorCode!==null)||receipt.state==='audio_ready'&&(a.kind!=='tts'||receipt.errorCode!==null))return false;
 if(['failed','outcome_unknown'].includes(receipt.state)&&receipt.audio!==null)return false;
 if(receipt.state==='audio_ready'){const audio=receipt.audio;if(!audio||audio.mime!=='audio/wav'||audio.container!=='wav'||audio.codec!=='pcm_s16le'||audio.sampleRate!==24000||audio.channels!==1||!audio.artifactId||!/^[a-f0-9]{64}$/.test(audio.sha256)||audio.sizeBytes!==audio.decodedSamples*2+44||audio.durationMs!==Math.round(audio.decodedSamples*1000/24000)||audio.durationMs<a.minDurationMs||audio.durationMs>a.maxDurationMs)return false;}
 const key=await crypto.subtle.importKey('raw',decode(p.publicKey).buffer as ArrayBuffer,{name:'ECDSA',namedCurve:'P-256'},false,['verify']);return crypto.subtle.verify({name:'ECDSA',hash:'SHA-256'},key,decode(receipt.signature).buffer as ArrayBuffer,encoder.encode(oneVaultCanonical(['receipt',oneVaultUnsigned(receipt)])));
 }catch{return false;}}
export function OneProviderControls({open,commandId,api,onClose,onSecuritySetup}:{open:boolean;commandId:string;api:OneProviderNativeAPI|null;onClose():void;onSecuritySetup?():Promise<void>}){
 const [boot,setBoot]=useState<OneProviderBootstrap|null>(null),[operation,setOperation]=useState<OneProviderPrepared|null>(null),[receipt,setReceipt]=useState<OneProviderReceipt|null>(null),[verification,setVerification]=useState<OneProviderReceipt|null>(null),[unknown,setUnknown]=useState(false),[error,setError]=useState<OneProviderErrorCode|null>(null),[busy,setBusy]=useState(false),[model,setModel]=useState(''),[voice,setVoice]=useState(''),[textRef,setTextRef]=useState('');const epoch=useRef(0),mounted=useRef(false);
 const close=()=>{++epoch.current;setBusy(false);onClose();};
 const load=async(captured:number)=>{if(!api)throw Error('provider_route_unavailable');const b=await api.bootstrap({commandId});if(captured!==epoch.current)return;if(!fresh(b,commandId))throw Error(b.errorCode??'authority_unavailable');setBoot(b);setModel(b.permittedModels[0]?.id??'');setVoice(b.permittedVoices[0]?.id??'');setTextRef(b.permittedTextRefs[0]?.ref??'');setOperation(b.activeOperation);setReceipt(null);setVerification(null);setUnknown(b.state==='outcome-unknown');if(b.activeOperation&&b.receipt){if(await authenticateOneProviderReceipt(b,b.activeOperation,b.receipt,b)){if(captured===epoch.current){setReceipt(b.receipt);if(b.receipt.state==='verified')setVerification(b.receipt);}}else throw Error('authority_denied');}if(captured===epoch.current)setError(b.errorCode);};
 useEffect(()=>{const captured=++epoch.current;mounted.current=open;setBoot(null);setOperation(null);setReceipt(null);setVerification(null);setUnknown(false);setError(null);setBusy(false);if(open){setBusy(true);void load(captured).catch(e=>{if(captured===epoch.current)setError(code(e))}).finally(()=>{if(captured===epoch.current)setBusy(false)});}return()=>{mounted.current=false;++epoch.current};},[open,commandId,api]);
 const current=async(captured:number,previous:OneProviderBootstrap)=>{if(!api)throw Error('provider_route_unavailable');const b=await api.bootstrap({commandId});if(captured!==epoch.current||!mounted.current)throw Error('authority_denied');if(!fresh(b,commandId))throw Error(b.errorCode??'authority_unavailable');if(b.credentialGeneration!==previous.credentialGeneration)throw Error('generation_changed');if(previous.resourceGrant&&previous.activeOperation&&retainedBinding(previous,previous.activeOperation)&&(!b.resourceGrant||b.resourceGrant.oneId!==previous.resourceGrant.oneId||b.resourceGrant.revision!==previous.resourceGrant.revision||b.resourceGrant.operationId!==previous.resourceGrant.operationId||b.resourceGrant.actionDigest!==previous.resourceGrant.actionDigest||oneVaultCanonical(b.resourceGrant.currentBinding)!==oneVaultCanonical(previous.resourceGrant.currentBinding)))throw Error('authority_denied');if(b.bindingKey!==previous.bindingKey||oneVaultCanonical(b.binding)!==oneVaultCanonical(previous.binding)||oneVaultCanonical(b.pinnedHost)!==oneVaultCanonical(previous.pinnedHost))throw Error('authority_denied');return b;};
 const work=async(action:(captured:number)=>Promise<void>)=>{if(busy)return;const captured=epoch.current;setBusy(true);setError(null);try{await action(captured)}catch(e){if(captured===epoch.current)setError(code(e))}finally{if(captured===epoch.current)setBusy(false)}};
 const prepare=(kind:'verify'|'tts')=>void work(async captured=>{if(!boot||!api||unknown||operation&&retainedBinding(boot,operation)||operation&&receipt?.state!=='verified')throw Error('authority_unavailable');if(kind==='tts'&&!verification&&receipt?.state!=='audio_ready')throw Error('provider_permission');const b=await current(captured,boot);const p=await api.prepare({commandId,kind,modelId:model,voiceId:voice,textRef:kind==='tts'?textRef:null});if(captured!==epoch.current)return;await current(captured,b);validatePrepared(b,p);if(p.action.kind!==kind||p.action.modelId!==model||p.action.voiceId!==voice||kind==='tts'&&p.action.textDigest!==b.permittedTextRefs.find(t=>t.ref===textRef)?.digest)throw Error('input_changed');setOperation(p);setReceipt(null);});
 const receive=async(captured:number,b:OneProviderBootstrap,p:OneProviderPrepared,r:OneProviderReceipt)=>{if(captured!==epoch.current)return;const observation=await current(captured,b);if(captured!==epoch.current)return;const historical=r.observedAt<Date.now()-120000||retainedBinding(b,p);if(!await authenticateOneProviderReceipt(b,p,r,historical?observation:undefined))throw Error('authority_denied');if(captured===epoch.current){setReceipt(r);if(r.state==='verified')setVerification(r);setUnknown(r.state==='outcome_unknown');setError(r.errorCode);}};
 const execute=()=>void work(async captured=>{if(!boot||!api||!operation||unknown||receipt)throw Error('authority_unavailable');const b=await current(captured,boot);validatePrepared(b,operation);setUnknown(true);let r:OneProviderReceipt;try{r=await api.execute({operationId:operation.operationId})}catch(e){if(captured===epoch.current){setUnknown(true);setError(code(e))}return;}await receive(captured,b,operation,r);});
 const status=()=>void work(async captured=>{if(!boot||!api||!operation)throw Error('authority_unavailable');const b=await current(captured,boot);await receive(captured,b,operation,await api.status({operationId:operation.operationId}));});
 const play=()=>void work(async captured=>{if(!boot||!api||!operation||!receipt||receipt.state!=='audio_ready')throw Error('audio_invalid');const b=await current(captured,boot);if(!await authenticateOneProviderReceipt(b,operation,receipt,receipt.observedAt<Date.now()-120000||retainedBinding(b,operation)?b:undefined))throw Error('audio_invalid');await api.openAudio({operationId:operation.operationId,receiptDigest:await oneProviderReceiptDigest(receipt)});});
 const readOnlyResult=!!boot&&!!operation&&retainedBinding(boot,operation);
 const blocked=!boot?.binding||!boot?.pinnedHost||boot.credentialGeneration===null||['key-missing','unavailable'].includes(boot.state)||!!error&&['authority_denied','authority_unavailable','generation_changed'].includes(error);
 const connected=!!verification||receipt?.state==='verified'||receipt?.state==='audio_ready',audio=receipt?.state==='audio_ready';
 return <OneBottomSheet open={open} onClose={close} ariaLabel="제공자 연결·음성" title="제공자 연결·음성" closeLabel="닫기" size="compact"><div className={styles.root}>
 <p>같은 원래 One 요청의 키 저장·제공자 연결 확인·음성 결과를 각각 확인합니다.</p><dl><dt>키 저장</dt><dd>{boot?.state!=='key-missing'&&boot?.credentialGeneration!==null&&boot?.credentialGeneration!==undefined?'저장 확인됨':'미확인 또는 없음'}</dd><dt>제공자 연결</dt><dd>{connected?(readOnlyResult?'이전 서명 결과 확인됨':'서명된 결과 확인됨'):'미확인'}</dd><dt>음성 결과</dt><dd>{audio?'검증된 WAV 준비됨':'없음 또는 미확인'}</dd></dl>
 {boot?.binding&&<div className={styles.context}><p>계정: {boot.accountLabel} · 역할: {boot.roleLabel}</p><p>범위: {boot.binding.scope==='personal'?'개인':`조직 ${boot.binding.organizationId}`} · host: {boot.binding.hostId}</p><p>{boot.binding.controlVersion===null&&boot.binding.taskId.startsWith("one:")?"대화 응답":"작업"}: {boot.binding.taskId} / 실행: {boot.binding.runId}</p><p>제공자: {boot.binding.provider} · {boot.binding.providerWorkspace} · {boot.binding.region}</p><p>저장: OS Vault · 키 세대: {boot.credentialGeneration??'미확인'} · 결제 주체: {boot.binding.payerId}</p><p>허용 권한: {boot.binding.operations.join(', ')}</p><p>{boot.retention.disclosure}</p></div>}
 {error&&<p role="status">{messages[error]}</p>}{unknown&&<p role="status">결과가 미확인입니다. 같은 작업의 상태를 확인하며 다시 실행하지 않습니다.</p>}
 {readOnlyResult&&<p role="status">이전 결과입니다. 현재 승인된 권한으로 상태와 검증된 음성만 확인할 수 있습니다.</p>}
 {(!operation||receipt?.state==='verified')&&!unknown&&!readOnlyResult&&<div className={styles.choices}><label>허용 모델<select value={model} disabled={busy||blocked} onChange={e=>setModel(e.target.value)}>{boot?.permittedModels.map(m=><option value={m.id} key={m.id}>{m.label}</option>)}</select></label><label>허용 음성<select value={voice} disabled={busy||blocked} onChange={e=>setVoice(e.target.value)}>{boot?.permittedVoices.map(v=><option value={v.id} key={v.id}>{v.label}</option>)}</select></label><label>원래 작업의 음성 입력<select value={textRef} disabled={busy||blocked} onChange={e=>setTextRef(e.target.value)}>{boot?.permittedTextRefs.map(t=><option value={t.ref} key={t.ref}>{t.label}</option>)}</select></label><div className={styles.actions}>{!connected&&<button disabled={busy||blocked||!model||!voice} onClick={()=>prepare('verify')}>연결 확인 준비</button>}<button disabled={busy||blocked||!connected||!model||!voice||!textRef} onClick={()=>prepare('tts')}>음성 생성 준비</button></div></div>}
 {operation&&<div className={styles.context}><p>작업 ID: {operation.operationId}</p><p>{readOnlyResult?'원래 작업의 견적 상한':'현재 견적 상한'}: {operation.quote.upperBoundMinor} {operation.quote.currency} (최소 화폐 단위) · 결제 주체: {operation.quote.payerId}</p><p>{readOnlyResult?"이전 견적은 새 실행 권한이나 현재 비용 승인이 아닙니다.":"실행 전에 native 창에서 현재 권한·비용·보관 정책 승인을 받습니다."}</p>{!unknown&&!receipt&&!readOnlyResult&&<button disabled={busy||blocked} onClick={execute}>권한·비용 확인 후 실행</button>}<button disabled={busy||blocked} onClick={status}>같은 작업 상태 확인</button></div>}
 {audio&&<p>WAV · PCM 16비트 · {receipt.audio!.sampleRate}Hz · {receipt.audio!.durationMs}ms <button disabled={busy||blocked} onClick={play}>검증된 음성 열기</button></p>}
 {onSecuritySetup&&boot?.state==='key-missing'&&<button disabled={busy} onClick={()=>void work(async captured=>{if(!boot)throw Error('authority_unavailable');await current(captured,boot);await onSecuritySetup();})}>native 보안 입력 안내 열기</button>}
 <div className={styles.actions}><button onClick={close}>취소·닫기</button>{!operation&&!unknown&&<button disabled={busy} onClick={()=>void work(load)}>현재 요청 다시 확인</button>}</div></div></OneBottomSheet>;
}
