"use client";
import { useEffect, useRef, useState } from "react";
import { ipc,ipcEvents } from "@/lib/ipc";
import type { OnePersonalDataAPI,PersonalDataTarget,PersonalDataSourceState,PersonalDataSpaceLink } from "@shared/one-personal-data";
import { OneBottomSheet } from "./OneBottomSheet";
import { OnePersonalDataPanel } from "./OnePersonalDataPanel";
import {OnePersonalIntegrationsPanel} from "./OnePersonalIntegrationsPanel";
import type {OnePersonalIntegrationsNativeAPI} from "@shared/one-personal-integrations";
import type {OnePersonalDataNativeAPI} from "@shared/one-personal-native";
import styles from "./OnePersonalDataPanel.module.css";
export interface PersonalDataFeatureBootstrap {
  state:"ready"|"blocked";target:PersonalDataTarget|null;targets:Array<{target:PersonalDataTarget;label:string}>;
  creatableScopes:Array<{scope:PersonalDataTarget["scope"];organizationId:string|null;projectId:string|null;label:string}>;
  budgetId:string|null;bindingKey:string;errorCode:string|null;
}
export interface OnePersonalDataFeatureAPI extends OnePersonalDataAPI {
  bootstrap(targetKey?:string):Promise<PersonalDataFeatureBootstrap>;
  listTargets():Promise<Array<{target:PersonalDataTarget;label:string}>>;
  createTarget(input:{commandId:string;scope:PersonalDataTarget["scope"];organizationId:string|null;projectId:string|null;title:string}):Promise<PersonalDataFeatureBootstrap>;
  selectTarget(input:{target:PersonalDataTarget}):Promise<PersonalDataFeatureBootstrap>;
  connectorCatalog(input:{target:PersonalDataTarget}):Promise<Array<{connectorId:string;label:string;state:"available"|"permission-required"|"unavailable"}>>;
  openSpaceLink?(input:{target:PersonalDataTarget;link:PersonalDataSpaceLink}):Promise<void>;
  registerSource(input:{target:PersonalDataTarget;connectorId:string}):Promise<PersonalDataSourceState>;
}
function targetKey(target:PersonalDataTarget){return JSON.stringify([target.deploymentId,target.oneId,target.scope,target.organizationId,target.projectId,target.spaceId,target.pageId,target.audience]);}
export function OnePersonalDataFeature(){
  const [integrations,setIntegrations]=useState(false);const [open,setOpen]=useState(false);const [panel,setPanel]=useState(false);const [bootstrap,setBootstrap]=useState<PersonalDataFeatureBootstrap|null>(null);const [catalog,setCatalog]=useState<Array<{connectorId:string;label:string;state:"available"|"permission-required"|"unavailable"}>>([]);const [newTitle,setNewTitle]=useState("");const [scopeIndex,setScopeIndex]=useState(0);const pendingCreate=useRef<Parameters<OnePersonalDataFeatureAPI["createTarget"]>[0]|null>(null);const [creatingUnknown,setCreatingUnknown]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState<string|null>(null);const epoch=useRef(0);
  const api=(ipc() as unknown as {onePersonalData?:OnePersonalDataFeatureAPI}|null)?.onePersonalData??null;
  const load=async()=>{const captured=++epoch.current;setBusy(true);setError(null);try{if(!api)throw new Error();const value=await api.bootstrap();if(captured!==epoch.current)return;setBootstrap(value);if(value.state==="ready"&&value.target){const choices=await api.connectorCatalog({target:value.target});if(captured===epoch.current)setCatalog(choices);}else setCatalog([]);}catch{if(captured===epoch.current){setBootstrap(null);setError("현재 계정의 Page·출처 권한을 확인할 수 없습니다.");}}finally{if(captured===epoch.current)setBusy(false);}};
  useEffect(()=>{if(open)void load();return()=>{++epoch.current;};},[open]);
  useEffect(()=>{if(!open||!api)return;const changed=()=>{const captured=epoch.current;void api.bootstrap().then(next=>{if(captured!==epoch.current)return;if(next.bindingKey!==bootstrap?.bindingKey||next.state!=="ready"){++epoch.current;setBootstrap(next);setCatalog([]);setPanel(false);setIntegrations(false);setBusy(false);}}).catch(()=>{if(captured===epoch.current){++epoch.current;setBootstrap(null);setPanel(false);setIntegrations(false);setBusy(false);setError("현재 권한을 확인할 수 없습니다.");}});};const off=ipcEvents()?.onStoreChanged?.(changed);return()=>off?.();},[open,api,bootstrap?.bindingKey]);
  useEffect(()=>{const invalidate=()=>{++epoch.current;setBootstrap(null);setCatalog([]);setPanel(false);setIntegrations(false);setBusy(false);setError("계정이 바뀌었습니다. 현재 Page·출처 권한을 다시 확인해 주세요.");pendingCreate.current=null;setCreatingUnknown(false);};const off=ipc()?.auth.onSessionChanged?.(invalidate);return()=>off?.();},[]);
  const close=()=>{++epoch.current;setOpen(false);setPanel(false);setIntegrations(false);setNewTitle("");setError(null);setBusy(false);pendingCreate.current=null;setCreatingUnknown(false);};
  const choose=async(target:PersonalDataTarget)=>{if(!api||busy)return;const captured=epoch.current;setBusy(true);try{const value=await api.selectTarget({target});if(value.state==="ready"&&(!value.target||targetKey(value.target)!==targetKey(target)))throw new Error();if(captured!==epoch.current)return;setBootstrap(value);const choices=value.target&&value.state==="ready"?await api.connectorCatalog({target:value.target}):[];if(captured===epoch.current)setCatalog(choices);}catch{if(captured===epoch.current)setError("이 Page의 현재 권한을 확인할 수 없습니다.");}finally{if(captured===epoch.current)setBusy(false);}};
  const create=async()=>{const scope=bootstrap?.creatableScopes[scopeIndex];if(!api||busy||(!pendingCreate.current&&(!scope||!newTitle.trim())))return;const captured=epoch.current;setBusy(true);const input=pendingCreate.current??{commandId:crypto.randomUUID(),scope:scope!.scope,organizationId:scope!.organizationId,projectId:scope!.projectId,title:newTitle};pendingCreate.current=input;try{const value=await api.createTarget(input);if(captured!==epoch.current)return;if(value.state!=="ready"||!value.target)throw new Error();setBootstrap(value);setNewTitle("");setCatalog([]);pendingCreate.current=null;setCreatingUnknown(false);}catch{if(captured===epoch.current){setCreatingUnknown(true);setError("Page 생성 결과를 확인할 수 없습니다. 같은 생성의 결과를 확인해 주세요.");}}finally{if(captured===epoch.current)setBusy(false);}};
  const register=async(connectorId:string)=>{if(!api||busy||!bootstrap?.target||bootstrap.state!=="ready")return;const captured=epoch.current;setBusy(true);try{const result=await api.registerSource({target:bootstrap.target,connectorId});if(captured!==epoch.current)return;if(!result.target||targetKey(result.target)!==targetKey(bootstrap.target)||result.binding.connectorId!==connectorId)throw new Error();setError("허용된 출처를 등록했습니다. 연결 상태는 실제 읽기 후 확인합니다.");}catch{if(captured===epoch.current)setError("출처 등록 또는 현재 권한을 확인할 수 없습니다.");}finally{if(captured===epoch.current)setBusy(false);}};
  return <><button type="button" aria-label="Page와 출처" onClick={()=>setOpen(true)} style={{minHeight:36,border:"1px solid var(--paper-edge)",borderRadius:9,color:"var(--ink)",background:"var(--paper)",padding:"6px 10px"}}>Page·출처</button>
    <OneBottomSheet open={open&&!panel&&!integrations} onClose={close} closeLabel="닫기" title="Page와 출처 선택"><div className={styles.root}><button type="button" disabled={busy} onClick={()=>void load()}>현재 목록 확인</button>{bootstrap?.state==="ready"?<><section className={styles.card}><h3>허용된 Pages</h3>{bootstrap.targets.map(item=><button type="button" key={JSON.stringify(item.target)} disabled={busy} onClick={()=>void choose(item.target)}>{item.label}</button>)}{bootstrap.target?<button type="button" className={styles.primary} disabled={busy} onClick={()=>setPanel(true)}>선택한 Page 열기</button>:<p>선택된 Page가 없습니다.</p>}</section>{bootstrap.creatableScopes.length?<section className={styles.card}><h3>새 Page</h3><label>허용된 범위<select disabled={busy||creatingUnknown} value={scopeIndex} onChange={event=>setScopeIndex(Number(event.target.value))}>{bootstrap.creatableScopes.map((scope,index)=><option value={index} key={index}>{scope.label}</option>)}</select></label><label>제목<input disabled={busy||creatingUnknown} value={newTitle} onChange={event=>setNewTitle(event.target.value)} /></label><button type="button" disabled={busy||creatingUnknown||!newTitle.trim()} onClick={()=>void create()}>새 Page 생성</button>{creatingUnknown?<button type="button" disabled={busy} onClick={()=>void create()}>같은 생성 결과 확인</button>:null}</section>:null}{bootstrap.target?<section className={styles.card}><button type="button" disabled={busy} onClick={()=>setIntegrations(true)}>Gmail과 기록 활용 열기</button><h3>사용 가능한 출처</h3>{catalog.length?catalog.map(source=><div className={styles.card} key={source.connectorId}><strong>{source.label}</strong><p>{source.state==="available"?"현재 권한으로 등록 가능":source.state==="permission-required"?"별도 권한 승인이 필요합니다.":"현재 사용할 수 없습니다."}</p><button type="button" disabled={busy||source.state!=="available"} onClick={()=>void register(source.connectorId)}>허용된 출처 등록</button></div>):<p>등록 가능한 출처를 확인할 수 없습니다.</p>}</section>:null}</>:<p role="status">{busy?"현재 계정의 범위를 확인하고 있습니다.":"현재 권한 또는 Page 대상을 확인할 수 없습니다."}</p>}{error?<p role="status" className={styles.notice}>{error}</p>:null}<button type="button" onClick={close}>닫기</button></div></OneBottomSheet>
    {bootstrap?.target&&bootstrap.state==="ready"?<OnePersonalIntegrationsPanel open={open&&integrations} onClose={()=>setIntegrations(false)} bootstrap={bootstrap} api={api as (OnePersonalDataNativeAPI&Partial<OnePersonalIntegrationsNativeAPI>)|null} supervisor={ipc()?.oneSupervisor??null}/>:null}
    {bootstrap?.target&&bootstrap.state==="ready"?<OnePersonalDataPanel open={open&&panel} api={api} target={bootstrap.target} currentBindingKey={bootstrap.bindingKey} budgetId={bootstrap.budgetId} onClose={()=>setPanel(false)} onOpenSpaceLink={api?.openSpaceLink?(link,target)=>api.openSpaceLink!({target,link}):undefined}/>:null}
  </>;
}
