"use client";
import { useCallback, useEffect, useRef, useState, type KeyboardEvent } from "react";
import type { OnePersonalDataAPI, PersonalDataTarget, PersonalDataSnapshot, PersonalDataWriteReceipt, PersonalDataSpaceLink, PersonalDataSourceStatus } from "@shared/one-personal-data";
import { OneBottomSheet } from "./OneBottomSheet";
import styles from "./OnePersonalDataPanel.module.css";
const sourceLabels:Record<PersonalDataSourceStatus,string>={unread:"아직 읽지 않음",ready:"실제 읽기 완료",partial:"일부만 읽음",invalid_cursor:"이어 읽기 위치 확인 필요",permission_changed:"권한 변경 · 다시 확인 필요",disconnected:"연결 해제됨",paused:"수집 일시 중지",blocked:"현재 읽기 불가"};
function sameTarget(a:PersonalDataTarget,b:PersonalDataTarget){return a.deploymentId===b.deploymentId&&a.oneId===b.oneId&&a.scope===b.scope&&a.organizationId===b.organizationId&&a.projectId===b.projectId&&a.spaceId===b.spaceId&&a.pageId===b.pageId&&a.audience===b.audience;}
function manualText(snapshot:PersonalDataSnapshot){return snapshot.page?.blocks.filter(block=>block.kind==="manual").map(block=>block.text).join("\n\n")??"";}
function safeError(error:unknown){const code=error&&typeof error==="object"&&"code" in error?(error as {code:unknown}).code:null;return code==="personal_data_revision_conflict"?"Page가 바뀌었습니다. 새 리비전과 초안을 비교한 뒤 다시 저장해 주세요.":code==="personal_data_authority_denied"?"현재 계정의 출처 또는 Page 권한을 확인해 주세요.":"결과를 확인할 수 없습니다. 새 작업을 시작하기 전에 같은 작업의 상태를 확인해 주세요.";}
type PendingWrite={run:()=>Promise<PersonalDataWriteReceipt>;commandId:string;expectedRevision:number};
export interface OnePersonalDataPanelProps {open:boolean;api:OnePersonalDataAPI|null;target:PersonalDataTarget;currentBindingKey:string;budgetId:string|null;onClose():void;onOpenSpaceLink?(link:PersonalDataSpaceLink,target:PersonalDataTarget):void|Promise<void>;}
export function OnePersonalDataPanel({open,api,target,currentBindingKey,budgetId,onClose,onOpenSpaceLink}:OnePersonalDataPanelProps){
  const [snapshot,setSnapshot]=useState<PersonalDataSnapshot|null>(null);const [title,setTitle]=useState("");const [text,setText]=useState("");const [baseRevision,setBaseRevision]=useState(0);const [dirty,setDirty]=useState(false);
  const dirtyRef=useRef(false);dirtyRef.current=dirty;const [busy,setBusy]=useState(false);const [feedback,setFeedback]=useState<string|null>(null);const [pendingWrite,setPendingWrite]=useState<PendingWrite|null>(null);const [followup,setFollowup]=useState("");const [followupPending,setFollowupPending]=useState(false);const followupOperation=useRef<{commandId:string;run:()=>ReturnType<OnePersonalDataAPI["followUp"]>}|null>(null);
  const epoch=useRef(0);const reading=useRef(0);const composing=useRef(false);const compositionEnded=useRef(0);const identity=JSON.stringify([target,currentBindingKey]);
  const refresh=useCallback(async()=>{if(!api)return;const captured=epoch.current;const serial=++reading.current;try{const value=await api.snapshot({target});if(captured!==epoch.current||serial!==reading.current)return;if(!sameTarget(value.target,target)||value.page&&!sameTarget(value.page.target,target)||value.sources.some(source=>!sameTarget(source.target,target))||value.proposals.some(proposal=>!sameTarget(proposal.target,target))||value.space&&value.space.spaceId!==target.spaceId)throw new Error("binding_mismatch");setSnapshot(value);if(!dirtyRef.current){setTitle(value.page?.title??"");setText(manualText(value));setBaseRevision(value.page?.revision??0);}}catch(error){if(captured===epoch.current&&serial===reading.current)setFeedback(safeError(error));}},[api,identity]);
  useEffect(()=>{++epoch.current;++reading.current;dirtyRef.current=false;setSnapshot(null);setTitle("");setText("");setBaseRevision(0);setDirty(false);setBusy(false);setPendingWrite(null);setFollowup("");setFollowupPending(false);followupOperation.current=null;setFeedback(null);if(open)void refresh();return()=>{++epoch.current;++reading.current;};},[open,identity,refresh]);
  const close=()=>{++epoch.current;++reading.current;onClose();};
  const guard=(event:KeyboardEvent<HTMLDivElement>)=>{if(event.key!=="Escape")return;event.stopPropagation();if(event.defaultPrevented||event.nativeEvent.isComposing||event.nativeEvent.keyCode===229||composing.current||Date.now()-compositionEnded.current<180)return;event.preventDefault();close();};
  const changed=!!snapshot&&(snapshot.page?.revision??0)!==baseRevision;
  const write=async(operation:PendingWrite)=>{if(busy)return;const captured=epoch.current;setBusy(true);setPendingWrite(operation);setFeedback(null);try{const result=await operation.run();if(captured!==epoch.current)return;if(!result.readBackVerified||result.commandId!==operation.commandId||!sameTarget(result.target,target)||!sameTarget(result.page.target,target)||result.revision!==operation.expectedRevision+1||result.page.revision!==result.revision||result.page.digest!==result.digest)throw new Error("readback_mismatch");dirtyRef.current=false;setDirty(false);setTitle(result.page.title);setText(result.page.blocks.filter(block=>block.kind==="manual").map(block=>block.text).join("\n\n"));setBaseRevision(result.revision);setPendingWrite(null);setFeedback(`리비전 ${result.revision} 저장 및 같은 내용 읽기 확인됨`);await refresh();}catch(error){if(captured===epoch.current)setFeedback(safeError(error));}finally{if(captured===epoch.current)setBusy(false);}};
  const save=()=>{if(!api||!snapshot||changed||pendingWrite||busy||!title.trim())return;const commandId=crypto.randomUUID();const input={commandId,target,title,text};const operation:PendingWrite={commandId,expectedRevision:baseRevision,run:()=>snapshot.page?api.edit({...input,expectedRevision:baseRevision}):api.create(input)};void write(operation);};
  const action=async(run:()=>Promise<unknown>,success:string,terminal=false)=>{if(busy&&!terminal)return;const captured=epoch.current;setBusy(true);setFeedback(null);try{await run();if(captured!==epoch.current)return;setFeedback(success);await refresh();}catch(error){if(captured===epoch.current)setFeedback(safeError(error));}finally{if(captured===epoch.current)setBusy(false);}};
  const sendFollowup=async(operation:{commandId:string;run:()=>ReturnType<OnePersonalDataAPI["followUp"]>})=>{if(busy)return;const captured=epoch.current;setBusy(true);setFollowupPending(true);try{const receipt=await operation.run();if(captured!==epoch.current)return;if(receipt.commandId!==operation.commandId||receipt.kind!=="follow-up"||receipt.acknowledgement==="unknown")throw new Error("followup_unknown");if(["failed","cancelled","held"].includes(receipt.state)){setFeedback("후속 요청이 실행되지 않았습니다. 현재 권한과 대화 상태를 확인해 주세요.");return;}setFollowup("");setFollowupPending(false);followupOperation.current=null;setFeedback("수락한 결과를 기준으로 후속 요청이 접수되었습니다. 실행 결과는 별도 확인합니다.");}catch(error){if(captured===epoch.current)setFeedback(safeError(error));}finally{if(captured===epoch.current)setBusy(false);}};
  const askFollowup=()=>{const page=snapshot?.page;if(!api||!page?.acceptedAnchor||busy||followupPending||!followup.trim()||dirty||changed)return;const commandId=crypto.randomUUID();const input={commandId,target,expectedRevision:page.revision,anchor:page.acceptedAnchor,text:followup};const operation={commandId,run:()=>api.followUp(input)};followupOperation.current=operation;void sendFollowup(operation);};
  return <OneBottomSheet open={open} onClose={close} closeLabel="닫기" title="Page와 출처" size="wide" closeOnEscape={false}>
    <div className={styles.root} data-testid="one-personal-data-panel" onKeyDown={guard} onCompositionStart={()=>{composing.current=true;}} onCompositionEnd={()=>{composing.current=false;compositionEnded.current=Date.now();}}>
      <p className={styles.subtle}>{target.scope==="organization"?`조직 ${target.organizationId}`:target.scope==="project"?"프로젝트":"개인"} · {target.audience==="organization"?"허용된 조직 대상":"소유자만"} · Space {target.spaceId} · Page {target.pageId}</p><div className={styles.actions}><button type="button" disabled={busy||!api} onClick={()=>void refresh()}>현재 상태 확인</button><button type="button" onClick={close}>닫기</button></div>
      {!snapshot?<p role="status" className={styles.notice}>{api?"출처와 Page 상태 확인 중":"개인 데이터 연결을 확인할 수 없습니다."}</p>:<>
        <section className={styles.card} aria-label="데이터 출처"><h3>출처</h3>{snapshot.sources.length===0?<p className={styles.subtle}>허용된 출처가 없습니다. 실제 읽기 전에는 연결 완료로 표시하지 않습니다.</p>:<ul className={styles.list}>{snapshot.sources.map(source=><li className={styles.card} key={source.binding.sourceId}><strong>{source.binding.connectorId} · {source.binding.accountRef}</strong><span className={styles.badge}>{source.status==="ready"&&source.observedAt&&source.sourceRevision?"연결 · 실제 읽기 완료":source.status==="ready"?"읽기 증거 확인 필요":sourceLabels[source.status]}</span><p className={styles.subtle}>마지막 읽기: {source.observedAt??"없음"} · {source.binding.coverage==="history"?"허용된 기록 범위":"제한된 검색 범위"} · 권한 {source.binding.permissionRevision}</p><div className={styles.actions}><button type="button" disabled={busy||!budgetId||["disconnected","paused","blocked","permission_changed","invalid_cursor"].includes(source.status)} onClick={()=>void action(()=>api!.collect({target,sourceId:source.binding.sourceId,budgetId:budgetId!}),"읽기 요청의 응답을 받았습니다. 최신 출처 상태를 확인해 주세요.")}>허용 범위 읽기</button><button type="button" disabled={source.status==="disconnected"} onClick={()=>void action(()=>api!.sourceControl({target,sourceId:source.binding.sourceId,action:source.status==="paused"?"resume":"pause",expectedRevision:source.revision}),source.status==="paused"?"수집 재개 요청 확인됨":"수집 중지 요청 확인됨",true)}>{source.status==="paused"?"수집 재개":"수집 일시 중지"}</button><button type="button" disabled={source.status==="disconnected"} onClick={()=>void action(()=>api!.sourceControl({target,sourceId:source.binding.sourceId,action:"disconnect",expectedRevision:source.revision}),"연결 해제 요청 확인됨 · 수동 Page는 보존됩니다.",true)}>연결 해제</button>{source.status==="invalid_cursor"?<button type="button" disabled={busy} onClick={()=>void action(()=>api!.sourceControl({target,sourceId:source.binding.sourceId,action:"reset-cursor",expectedRevision:source.revision}),"이어 읽기 위치 초기화 확인됨")}>읽기 위치 초기화</button>:null}</div></li>)}</ul>}</section>
        <section className={styles.card} aria-label="Page 편집"><h3>Page 편집</h3><p className={styles.revision}>리비전 {snapshot.page?.revision??0} · 마지막 업데이트 {snapshot.page?.updatedAt??"없음"}</p><label>제목<input value={title} disabled={busy||!!pendingWrite} onChange={event=>{dirtyRef.current=true;setDirty(true);setTitle(event.target.value);}} /></label><label>내가 편집한 내용<textarea value={text} disabled={busy||!!pendingWrite} onChange={event=>{dirtyRef.current=true;setDirty(true);setText(event.target.value);}} data-testid="one-page-manual-text" /></label>{changed?<p role="alert" className={styles.notice}>편집 중 Page가 바뀌었습니다. 내 초안은 유지됩니다. 새 내용을 확인하고 명시적으로 합친 뒤 저장해 주세요.<br/>현재 저장된 수동 내용: {manualText(snapshot)}</p>:null}<div className={styles.actions}><button type="button" className={styles.primary} disabled={busy||!!pendingWrite||changed||!title.trim()||(!dirty&&!!snapshot.page)} onClick={save}>수동 편집 저장</button>{pendingWrite?<button type="button" disabled={busy} onClick={()=>void write(pendingWrite)}>같은 저장 결과 확인</button>:null}{changed&&!pendingWrite?<button type="button" disabled={busy} onClick={()=>{setBaseRevision(snapshot.page?.revision??0);setFeedback("새 리비전을 기준으로 내 초안을 유지합니다. 내용을 비교하고 저장해 주세요.");}}>비교·병합한 초안으로 저장 준비</button>:null}</div>{snapshot.page?.blocks.filter(block=>block.kind==="inference").map(block=><article className={styles.card} key={block.id}><strong>수락한 추론 내용</strong><p className={styles.proposal}>{block.text}</p><p className={styles.subtle}>출처: {block.sourceRefs.join(", ")||"표시할 출처 없음"}</p></article>)}</section>
        <section className={styles.card} aria-label="변경 제안"><h3>변경 제안과 승인</h3>{!snapshot.proposals.length?<p className={styles.subtle}>새 제안이 없습니다.</p>:snapshot.proposals.map(proposal=><article className={styles.card} key={proposal.proposalId}><strong>{proposal.status==="accepted"?"수락됨":proposal.status==="cancelled"?"취소됨":"검토 및 승인 필요"}</strong><p className={styles.subtle}>기준 리비전 {proposal.baseRevision} · {proposal.createdAt}</p>{proposal.blocks.map(block=><p className={styles.proposal} key={block.id}>{block.text}</p>)}<p className={styles.subtle}>출처: {proposal.sourceBindings.map(source=>`${source.connectorId} · ${source.accountRef}`).join(", ")}</p>{proposal.status==="pending"?<div className={styles.actions}><button type="button" disabled={busy||dirty||changed||!!pendingWrite||proposal.baseRevision!==(snapshot.page?.revision??0)} onClick={()=>{const commandId=crypto.randomUUID();void write({commandId,expectedRevision:proposal.baseRevision,run:()=>api!.accept({commandId,target,proposalId:proposal.proposalId,expectedRevision:proposal.baseRevision})});}}>검토한 변경 승인·수락</button><button type="button" disabled={busy} onClick={()=>void action(()=>api!.cancelProposal({target,proposalId:proposal.proposalId}),"제안 취소 요청 확인됨")}>제안 취소</button></div>:null}</article>)}</section>
        {snapshot.space?<section className={styles.card} aria-label="Space 연결"><h3>같은 Space의 연결</h3><div className={styles.links}>{snapshot.space.links.map(link=><button type="button" key={`${link.kind}:${link.ref}`} disabled={!onOpenSpaceLink} onClick={()=>void action(()=>Promise.resolve(onOpenSpaceLink?.(link,target)),"연결 열기 요청의 응답을 받았습니다.")}>{link.kind==="page"?"Page":link.kind==="conversation"?"대화":"파일"} · {link.label}</button>)}</div></section>:null}
        {snapshot.page?.acceptedAnchor?<section className={styles.card} aria-label="수락한 결과 후속 요청"><h3>수락한 결과에서 이어 하기</h3><p className={styles.subtle}>{snapshot.page.acceptedAnchor.artifactId} · 리비전 {snapshot.page.acceptedAnchor.artifactRevision}</p><label>후속 요청<textarea value={followup} disabled={busy||followupPending} onChange={event=>setFollowup(event.target.value)} /></label><button type="button" disabled={busy||followupPending||dirty||changed||!followup.trim()} onClick={()=>void askFollowup()}>이 수락 결과로 후속 요청</button>{followupPending&&followupOperation.current?<button type="button" disabled={busy} onClick={()=>void sendFollowup(followupOperation.current!)}>같은 후속 요청 확인</button>:null}</section>:null}
      </>}{feedback?<p role="status" className={styles.notice}>{feedback}</p>:null}
    </div>
  </OneBottomSheet>;
}
