'use client';
import {useEffect,useRef,useState} from 'react';
import {ipc,ipcEvents} from '@/lib/ipc';
import type {OneProviderBootstrap,OneProviderNativeAPI} from '@shared/one-provider-native';
import type {OneSupervisorSnapshot,SupervisorCommandReceipt} from '@shared/one-supervisor';
import {OneBottomSheet} from '@/components/one/OneBottomSheet';
import {OnePersonalDataFeature} from '@/components/one/OnePersonalDataFeature';
import {OneProviderFeature} from '@/components/one/OneProviderFeature';
import {OneVaultRecoveryFeature} from './OneVaultRecoveryFeature';
/** Optional until Main's real native bridge is registered; no fallback provider implementation. */
function providerAPI():OneProviderNativeAPI|null {const candidate=(ipc() as (ReturnType<typeof ipc>&{oneProvider?:OneProviderNativeAPI}))?.oneProvider;return candidate&&['bootstrap','prepare','execute','status','openAudio'].every(method=>typeof candidate[method as keyof OneProviderNativeAPI]==='function')?candidate:null;}
function eligibleRequest(item:SupervisorCommandReceipt){return !!item.runId&&!['cancelled','failed','held'].includes(item.state)&&(!!item.taskId||item.kind==='reply'&&item.taskId===null&&['dispatching','accepted'].includes(item.state));}
function sameOriginal(a:SupervisorCommandReceipt,b:SupervisorCommandReceipt){return a.commandId===b.commandId&&a.kind===b.kind&&a.taskId===b.taskId&&a.runId===b.runId;}
function nativeOriginal(boot:OneProviderBootstrap,receipt:SupervisorCommandReceipt,snapshot:OneSupervisorSnapshot){const b=boot.binding;if(!b||!boot.pinnedHost||boot.commandId!==receipt.commandId||b.commandId!==receipt.commandId||b.runId!==receipt.runId||!b.authorityRevision||boot.expiresAt<=Date.now()||boot.observedAt<Date.now()-120000||boot.observedAt>Date.now()+30000)return false;return receipt.taskId?b.taskId===receipt.taskId&&typeof b.controlVersion==='string'&&!!b.controlVersion:receipt.kind==='reply'&&b.taskId===`one:${snapshot.conversationChatId}`&&b.controlVersion===null;}
export function OneSecurityFeatures(){
 const [open,setOpen]=useState(false),[snapshot,setSnapshot]=useState<OneSupervisorSnapshot|null>(null),[selected,setSelected]=useState<SupervisorCommandReceipt|null>(null),[error,setError]=useState<string|null>(null),[busy,setBusy]=useState(false),[authorityEpoch,setAuthorityEpoch]=useState(0);const epoch=useRef(0);const api=ipc();
 const close=()=>{++epoch.current;setOpen(false);setBusy(false);setSelected(null);setSnapshot(null);};
 useEffect(()=>{const invalidate=()=>{close();setAuthorityEpoch(v=>v+1)};const offSession=ipc()?.auth.onSessionChanged?.(invalidate),offStore=ipcEvents()?.onStoreChanged?.(change=>{if(['auth','permissions','workspace','host-trust','vault'].includes(change.entity))invalidate()});return()=>{++epoch.current;offSession?.();offStore?.();};},[]);
 const show=async()=>{const captured=++epoch.current;setOpen(true);setSelected(null);setSnapshot(null);setBusy(true);setError(null);try{const value=await ipc()?.oneSupervisor.snapshot();if(captured!==epoch.current)return;if(!value||value.schema!=='agentlas.one-supervisor.v1')throw Error();setSnapshot(value);}catch{if(captured===epoch.current)setError('현재 One의 원래 요청 목록을 확인할 수 없습니다.');}finally{if(captured===epoch.current)setBusy(false)}};
 const select=async(receipt:SupervisorCommandReceipt)=>{if(!snapshot||busy)return;const captured=epoch.current;setBusy(true);setError(null);setSelected(null);try{const native=providerAPI();if(!native)throw Error('route_unavailable');const current=await ipc()?.oneSupervisor.receipt({oneId:snapshot.oneId,commandId:receipt.commandId});if(captured!==epoch.current)return;if(!current||!sameOriginal(current,receipt)||!eligibleRequest(current))throw Error();const boot=await native.bootstrap({commandId:current.commandId});if(captured!==epoch.current)return;const latest=await ipc()?.oneSupervisor.snapshot();if(captured!==epoch.current)return;const matches=latest?.requests.filter(item=>item.commandId===current.commandId)??[];if(!latest||latest.schema!=='agentlas.one-supervisor.v1'||latest.oneId!==snapshot.oneId||matches.length!==1||!sameOriginal(matches[0],current)||!eligibleRequest(matches[0])||!nativeOriginal(boot,current,latest))throw Error();setSelected(matches[0]);}catch(e){if(captured===epoch.current)setError(e instanceof Error&&e.message==='route_unavailable'?'제공자 요청의 현재 권한을 확인할 연결이 없습니다.':'원래 요청의 실행·권한을 확인할 수 없습니다. 다른 요청과 합치거나 새 실행을 만들지 않습니다.');}finally{if(captured===epoch.current)setBusy(false)}};
 const counts=new Map<string,number>();for(const item of snapshot?.requests??[])counts.set(item.commandId,(counts.get(item.commandId)??0)+1);const ambiguous=[...counts.values()].some(count=>count>1);const candidates=snapshot?.requests.filter(item=>eligibleRequest(item)&&counts.get(item.commandId)===1)??[];const provider=providerAPI();
 return <div style={{display:'flex',flexWrap:'wrap',gap:8,maxWidth:'calc(100vw - 32px)'}}><OnePersonalDataFeature/><OneVaultRecoveryFeature api={api?.oneVault??null} authorityEpoch={authorityEpoch}/><button onClick={()=>void show()}>원래 요청의 제공자·음성</button><OneBottomSheet open={open} onClose={close} ariaLabel="제공자 원래 요청 선택" title="제공자 원래 요청 선택" closeLabel="닫기" size="compact"><div style={{display:'flex',flexDirection:'column',gap:12,overflowWrap:'anywhere'}}>
 <p>기존 Supervisor 기록의 원래 요청을 선택합니다. 새 실행이나 명령을 만들지 않습니다.</p>{!provider&&<p role="status">제공자 연결을 확인할 기능이 준비되지 않았습니다. 연결과 음성 사용 가능 여부는 아직 확인되지 않았습니다.</p>}{error&&<p role="status">{error}</p>}{!busy&&!snapshot&&<p>원래 요청 목록 미확인</p>}{snapshot&&!candidates.length&&<p>선택할 수 있는 원래 작업·대화 응답 요청이 없습니다.</p>}
 {ambiguous&&<p role="status">같은 요청 ID의 기록이 겹칩니다. 정확한 원래 요청을 구분하기 전에는 선택할 수 없습니다.</p>}{candidates.map(item=><button key={item.commandId} disabled={busy} onClick={()=>void select(item)}>{item.taskId?'원래 작업 요청':'원래 대화 응답'} {item.commandId} · {item.taskId?`${item.taskId} / `:''}{item.runId}</button>)}
 {selected&&<div><p>선택한 원래 요청: {selected.commandId} · {selected.taskId?`${selected.taskId} / `:'대화 응답 실행 '}{selected.runId}</p><OneProviderFeature key={selected.commandId} commandId={selected.commandId} api={provider}/></div>}<button onClick={close}>취소·닫기</button></div></OneBottomSheet></div>;
}
